/*
 * SPDX-FileCopyrightText: Copyright (c) 2020-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "Tests/RenderTests/GfxDriver/GfxDriverTestFixtures.h"

#include <memory>
#include <random>
#include <string>
#include <vector>

#include <glm/gtc/quaternion.hpp>
#include <glm/mat4x4.hpp>
#include <glm/vec3.hpp>
#include <glm/vec4.hpp>

#include "GfxDriver/Colors/GlmUtils.h"
#include "GfxDriver/Drivers/Vulkan/VulkanPlatform.h"
#include "GfxDriver/Pipeline/Material.h"
#include "GfxDriver/Pipeline/Pipeline.h"
#include "GfxDriver/Pipeline/PipelineDescriptor.h"
#include "GfxDriver/Render/Camera.h"
#include "GfxDriver/Render/LightManager.h"
#include "GfxDriver/Render/PBRMaterialManager.h"
#include "GfxDriver/Render/PBRScene.h"
#include "GfxDriver/Resources/BufferLayout.h"
#include "GfxDriver/Resources/Texture.h"
#include "GfxDriver/Resources/VertexBuffer.h"
#include "GfxDriver/ShaderCompiler/ShaderManager.h"
#include "Shared/measure.h"
#include "Tests/RenderTests/Utils/AttachmentUtils.h"
#include "Tests/RenderTests/Utils/GoldenImage.h"
#include "Tests/RenderTests/Utils/MeshUtils.h"
#include "Tests/RenderTests/Utils/ShaderUtils.h"

#define SHOW_IMAGE_LOAD_STORE_STATS 0
#if SHOW_IMAGE_LOAD_STORE_STATS
#include <iostream>
#endif

/**
 * GfxRenderTests
 *
 * - Golden image tests
 *
 * - Shader files can be added using the ShaderManifest.json file
 *   in the path specified by g_shaders_path
 *
 * - All images using RenderTestBase can be regenerated by enabling
 *   regenerate_golden_images below
 *
 * */
namespace GfxDriverTests {

// Render dimensions for all tests (golden images 320x240)
static constexpr uint32_t render_width = 320;
static constexpr uint32_t render_height = 240;

// Flag to force writing of all golden image files
static constexpr bool regenerate_golden_images = false;

// File paths
namespace {
static std::string g_golden_images_path(std::string(RENDER_TESTS_PATH) +
                                        "GfxDriver/golden_images/");

static std::string_view kTestFlushName{"GfxRenderTest"};

}  // namespace

//
// RenderTestBase fixture template
//
template <typename GTEST_BASE,
          typename DRIVER_TYPE,
          typename SHADER_LIBRARY = GfxDriverTestShaderLibrary>
class RenderTestBase : public DeviceContextTest<GTEST_BASE, DRIVER_TYPE, SHADER_LIBRARY> {
 protected:
  using Base = DeviceContextTest<GTEST_BASE, DRIVER_TYPE, SHADER_LIBRARY>;

  void SetUp() override {
    Base::SetUp();
    golden_image_ = std::make_unique<GoldenImage>(
        g_golden_images_path, this->driver_->getType(), regenerate_golden_images);
  }
  void TearDown() override { Base::TearDown(); }

  std::unique_ptr<GoldenImage> golden_image_;
};

using VulkanRenderTest = RenderTestBase<::testing::Test, VulkanDriver>;

#define USE_TYPED_TEST 0

#if USE_TYPED_TEST
template <typename DRIVER_TYPE>
using TypedRenderTest =
    RenderTestBase<::testing::Test, DRIVER_TYPE, GfxDriverTestShaderLibrary>;
TYPED_TEST_SUITE(TypedRenderTest, DriverTypes);
#else
using RenderTest = VulkanRenderTest;
#endif

//
// Draw Fullscreen Triangle
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, DrawFullscreenTriangle) {
#else
TEST_F(RenderTest, DrawFullscreenTriangle) {
#endif
  // begin_renderdoc_vulkan_capture();
  auto& device = *this->device_contexts_[0];

  // Generate spirv
  auto caches = this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
      {{"DriverTests/fullScreenTriangle.vert"}, {"RenderTests/drawFullScreenTest.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("Test", caches);
  ASSERT_NE(material, nullptr);
  std::array<float, 2> dimensions{static_cast<float>(render_width),
                                  static_cast<float>(render_height)};
  material->setUniformAttribute("imageSize", dimensions);
  material->setUniformAttribute("invertY", 0);

  material->updateDescriptorSets();

  // attachment manager and textures
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        render_width,
                        render_height,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

  // renderpass and framebuffer
  auto render_pass = resource_mgr.createRenderPass("Test",
                                                   attachment_mgr.getLayout(),
                                                   gfx::RenderPass::ClearBits::kAll,
                                                   ImageLayout::kUndefined,
                                                   ImageLayout::kAttachment);
  ASSERT_NE(render_pass, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer(
      "Test", *render_pass, attachment_mgr, render_width, render_height, 1u);
  ASSERT_NE(framebuffer, nullptr);

  // pipeline
  PipelineDescriptor pipeline_desc;
  auto pipeline = resource_mgr.createGraphicsPipeline("Test", *material, pipeline_desc);
  pipeline->create(*render_pass);

  // Deliberately call pipeline->create twice to ensure recreating works properly
  pipeline->create(*render_pass);

  // render via command list
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();
  cmd_list.beginRenderPass(*render_pass, *framebuffer)
      .drawFullscreen(*pipeline)
      .endRenderPass()
      .flush(kTestFlushName);

  // Compare to golden image
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "draw_fullscreen_test"));

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  material = nullptr;
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
  // end_renderdoc_vulkan_capture();
}

//
// Draw One Triangle
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, DrawOneTriangle) {
#else
TEST_F(RenderTest, DrawOneTriangle) {
#endif
  // begin_renderdoc_vulkan_capture();
  auto& device = *this->device_contexts_[0];

  // Generate spirv
  auto caches = this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
      {{"RenderTests/drawOneTriangleTest.vert"},
       {"RenderTests/drawOneTriangleTest.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("Test", caches);
  ASSERT_NE(material, nullptr);

  // attachment manager and textures
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        render_width,
                        render_height,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

  // renderpass and framebuffer
  auto render_pass = resource_mgr.createRenderPass("Test",
                                                   attachment_mgr.getLayout(),
                                                   gfx::RenderPass::ClearBits::kAll,
                                                   ImageLayout::kUndefined,
                                                   ImageLayout::kAttachment);
  ASSERT_NE(render_pass, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer(
      "Test", *render_pass, attachment_mgr, render_width, render_height, 1u);
  ASSERT_NE(framebuffer, nullptr);

  // vertex buffer, layout, and attr map
  auto buffer_layout = std::make_shared<InterleavedBufferLayout>();
  ASSERT_NE(buffer_layout, nullptr);
  buffer_layout->addAttribute("in_position", BufferAttrType::kVec2f);
  buffer_layout->addAttribute("in_color", BufferAttrType::kVec3f);

  // clang-format off
  std::array<float, 15> vertex_data{-0.5f,  0.5f,  1.0f, 0.0f, 0.0f,
                                     0.0f, -0.5f,  0.0f, 1.0f, 0.0f,
                                     0.5f,  0.5f,  0.0f, 0.0f, 1.0f};
  // clang-format on

  auto vertex_buffer_wrapper =
      resource_mgr.createBuffer("Test",
                                {BufferType::kVertexBuffer,
                                 vertex_data.size() * sizeof(float),
                                 BufferUsageBits::kLayoutBufferBit});
  ASSERT_NE(vertex_buffer_wrapper, nullptr);

  auto* vertex_buffer = static_cast<VertexBuffer*>(vertex_buffer_wrapper.get());
  vertex_buffer->updateSubDataWithLayout(
      vertex_data.data(), vertex_buffer->getNumBytes(), 0, buffer_layout);

  PrimitiveAssemblyAttrInfo attr_info{
      {vertex_buffer, buffer_layout},
      {{"in_position", "in_position"}, {"in_color", "in_color"}}};

  // pipeline
  auto primitive_assembly = resource_mgr.createPrimitiveAssembly(
      "Test", PrimitiveTopology::kTriangleList, *material, attr_info);
  PipelineDescriptor pipeline_desc;
  auto pipeline = resource_mgr.createGraphicsPipeline(
      "Test", *material, pipeline_desc, primitive_assembly.get());

  pipeline->create(*render_pass);

  // render via command list
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();
  cmd_list.beginRenderPass(*render_pass, *framebuffer)
      .drawVertices(*pipeline, *vertex_buffer, 3)
      .endRenderPass()
      .flush(kTestFlushName);

  // Compare to golden image
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "draw_one_triangle_test"));

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  material = nullptr;
  resource_mgr.destroyBuffer(std::move(vertex_buffer_wrapper));
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
  // end_renderdoc_vulkan_capture();
}

//
// External Uniform Buffer
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, ExternalUniformBuffer) {
#else
TEST_F(RenderTest, ExternalUniformBuffer) {
#endif
  // begin_renderdoc_vulkan_capture();
  auto& device = *this->device_contexts_[0];

  // Generate spirv
  auto builders1 = this->gfx_context_->getShaderManager().createBuilderVector(
      {{"RenderTests/externalUniformBufferTest1.vert"},
       {"RenderTests/externalUniformBufferTest1.frag"}});
  ASSERT_NE(builders1.size(), size_t{0});
  builders1[0]->setExternalUniformBuffers({"EXTERNAL_UBO"});
  builders1[1]->setExternalUniformBuffers({"EXTERNAL_UBO"});
  auto caches1 =
      this->gfx_context_->getShaderManager().createCacheVector(std::move(builders1));
  ASSERT_TRUE(validate_shader_caches(caches1));

  auto builders2 = this->gfx_context_->getShaderManager().createBuilderVector(
      {{"RenderTests/externalUniformBufferTest2.vert"},
       {"RenderTests/externalUniformBufferTest2.frag"}});
  ASSERT_NE(builders2.size(), size_t{0});
  builders2[0]->setExternalUniformBuffers({"EXTERNAL_UBO"});
  builders2[1]->setExternalUniformBuffers({"EXTERNAL_UBO"});
  auto caches2 =
      this->gfx_context_->getShaderManager().createCacheVector(std::move(builders2));
  ASSERT_TRUE(validate_shader_caches(caches2));

  auto& resource_mgr = device.getResourceManager();

  // external uniform buffer
  struct ExternalUniformBuffer {
    float vert_value;
    float frag_value;
  };
  auto external_uniform_buffer_wrapper = resource_mgr.createBuffer(
      "External Uniform Buffer",
      {BufferType::kUnspecified,
       8,
       BufferUsageBits::kUniformBufferBit | BufferUsageBits::kLayoutBufferBit,
       BufferAccessType::kHostVisible});

  // material
  auto material1 = resource_mgr.createMaterial("Test1", caches1);
  ASSERT_NE(material1, nullptr);
  auto material2 = resource_mgr.createMaterial("Test2", caches2);
  ASSERT_NE(material2, nullptr);

  // attachment manager and textures
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        render_width,
                        render_height,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

  // renderpass and framebuffer
  auto render_pass1 = resource_mgr.createRenderPass("Test 1",
                                                    attachment_mgr.getLayout(),
                                                    gfx::RenderPass::ClearBits::kAll,
                                                    ImageLayout::kUndefined,
                                                    ImageLayout::kAttachment);
  ASSERT_NE(render_pass1, nullptr);
  auto render_pass2 = resource_mgr.createRenderPass("Test 2",
                                                    attachment_mgr.getLayout(),
                                                    gfx::RenderPass::ClearBits::kNone,
                                                    ImageLayout::kAttachment,
                                                    ImageLayout::kAttachment);
  ASSERT_NE(render_pass2, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer(
      "Test", *render_pass1, attachment_mgr, render_width, render_height, 1u);
  ASSERT_NE(framebuffer, nullptr);

  // vertex buffer, layout, and attr map
  auto buffer_layout = std::make_shared<InterleavedBufferLayout>();
  ASSERT_NE(buffer_layout, nullptr);
  buffer_layout->addAttribute("in_position", BufferAttrType::kVec2f);
  buffer_layout->addAttribute("in_color", BufferAttrType::kVec3f);

  // clang-format off
  std::array<float, 15> vertex_data{-0.5f,  0.5f,  1.0f, 0.0f, 0.0f,
                                     0.0f, -0.5f,  0.0f, 1.0f, 0.0f,
                                     0.5f,  0.5f,  0.0f, 0.0f, 1.0f};
  // clang-format on

  auto vertex_buffer_wrapper =
      resource_mgr.createBuffer("Test",
                                {BufferType::kVertexBuffer,
                                 vertex_data.size() * sizeof(float),
                                 BufferUsageBits::kLayoutBufferBit});
  ASSERT_NE(vertex_buffer_wrapper, nullptr);

  auto* vertex_buffer = static_cast<VertexBuffer*>(vertex_buffer_wrapper.get());
  vertex_buffer->updateSubDataWithLayout(
      vertex_data.data(), vertex_buffer_wrapper->getNumBytes(), 0, buffer_layout);

  PrimitiveAssemblyAttrInfo attr_info{
      {vertex_buffer, buffer_layout},
      {{"in_position", "in_position"}, {"in_color", "in_color"}}};

  // pipeline
  auto primitive_assembly1 = resource_mgr.createPrimitiveAssembly(
      "Test1", PrimitiveTopology::kTriangleList, *material1, attr_info);
  auto primitive_assembly2 = resource_mgr.createPrimitiveAssembly(
      "Test2", PrimitiveTopology::kTriangleList, *material2, attr_info);
  PipelineDescriptor pipeline_desc;
  auto pipeline1 = resource_mgr.createGraphicsPipeline(
      "Test1", *material1, pipeline_desc, primitive_assembly1.get());
  pipeline1->create(*render_pass1);
  auto pipeline2 = resource_mgr.createGraphicsPipeline(
      "Test2", *material2, pipeline_desc, primitive_assembly2.get());
  pipeline2->create(*render_pass2);

  // bind external uniform buffer
  material1->bindExternalUniformBufferToBlock("EXTERNAL_UBO",
                                              *external_uniform_buffer_wrapper);
  material2->bindExternalUniformBufferToBlock("EXTERNAL_UBO",
                                              *external_uniform_buffer_wrapper);

  // set values in external uniform buffer
  ExternalUniformBuffer eub;
  eub.vert_value = 0.2;
  eub.frag_value = 0.5;
  external_uniform_buffer_wrapper->updateSubData(&eub, sizeof(eub), 0);

  // update materials
  material1->updateDescriptorSets();
  material2->updateDescriptorSets();

  // render via command list
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();
  cmd_list.beginRenderPass(*render_pass1, *framebuffer)
      .drawVertices(*pipeline1, *vertex_buffer, 3)
      .endRenderPass()
      .flush(kTestFlushName);
  cmd_list.beginRenderPass(*render_pass2, *framebuffer)
      .drawVertices(*pipeline2, *vertex_buffer, 3)
      .endRenderPass()
      .flush(kTestFlushName);

  // Compare to golden image
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "external_uniform_buffer_test"));

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline1));
  resource_mgr.destroyPipeline(std::move(pipeline2));
  material1 = nullptr;
  material2 = nullptr;
  primitive_assembly1 = nullptr;
  primitive_assembly2 = nullptr;
  resource_mgr.destroyBuffer(std::move(external_uniform_buffer_wrapper));
  resource_mgr.destroyBuffer(std::move(vertex_buffer_wrapper));
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass1));
  resource_mgr.destroyRenderPass(std::move(render_pass2));
  // end_renderdoc_vulkan_capture();
}

//
// Push constant test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, PushConstantTest) {
#else
TEST_F(RenderTest, PushConstantTest) {
#endif
  // begin_renderdoc_vulkan_capture();
  auto& device = *this->device_contexts_[0];

  // Generate spirv
  auto caches = this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
      {{"RenderTests/pushConstantTest.vert"}, {"RenderTests/pushConstantTest.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("Test", caches);
  ASSERT_NE(material, nullptr);

  // attachment manager and textures
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        render_width,
                        render_height,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

  // renderpass and framebuffer
  auto render_pass = resource_mgr.createRenderPass("Test",
                                                   attachment_mgr.getLayout(),
                                                   gfx::RenderPass::ClearBits::kAll,
                                                   ImageLayout::kUndefined,
                                                   ImageLayout::kAttachment);
  ASSERT_NE(render_pass, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer(
      "Test", *render_pass, attachment_mgr, render_width, render_height, 1u);
  ASSERT_NE(framebuffer, nullptr);

  // vertex buffer, layout, and attr map
  auto buffer_layout = std::make_shared<InterleavedBufferLayout>();
  ASSERT_NE(buffer_layout, nullptr);
  buffer_layout->addAttribute("in_position", BufferAttrType::kVec2f);

  constexpr float triangle_size = 0.1f;
  std::array<float, 6> vertex_data{
      -triangle_size, triangle_size, 0.0f, -triangle_size, triangle_size, triangle_size};

  auto vertex_buffer_wrapper =
      resource_mgr.createBuffer("Test",
                                {BufferType::kVertexBuffer,
                                 vertex_data.size() * sizeof(float),
                                 BufferUsageBits::kLayoutBufferBit});
  ASSERT_NE(vertex_buffer_wrapper, nullptr);

  auto* vertex_buffer = static_cast<VertexBuffer*>(vertex_buffer_wrapper.get());
  vertex_buffer->updateSubDataWithLayout(
      vertex_data.data(), vertex_buffer_wrapper->getNumBytes(), 0, buffer_layout);

  PrimitiveAssemblyAttrInfo attr_info{{vertex_buffer, buffer_layout},
                                      {{"in_position", "in_position"}}};

  // pipeline
  auto primitive_assembly = resource_mgr.createPrimitiveAssembly(
      "Test", PrimitiveTopology::kTriangleList, *material, attr_info);
  PipelineDescriptor pipeline_desc;
  pipeline_desc.getPushConstantRanges().insert(
      ShaderStageBits::kVertex, 0, sizeof(uint32_t));
  auto pipeline = resource_mgr.createGraphicsPipeline(
      "Test", *material, pipeline_desc, primitive_assembly.get());

  pipeline->create(*render_pass);

  // render via command list
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();
  cmd_list.beginRenderPass(*render_pass, *framebuffer);
  for (uint32_t i = 0; i < 5; ++i) {
    cmd_list.setPushConstantUInt32(*pipeline, "index", ShaderStageBits::kVertex, i);
    cmd_list.drawVertices(*pipeline, *vertex_buffer, 3);
  }
  cmd_list.endRenderPass().flush(kTestFlushName);

  // Compare to golden image
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "push_constant_test"));

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  material = nullptr;
  resource_mgr.destroyBuffer(std::move(vertex_buffer_wrapper));
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
  // end_renderdoc_vulkan_capture();
}

//
// Depth test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, DepthTest) {
#else
TEST_F(RenderTest, DepthTest) {
#endif
  // begin_renderdoc_vulkan_capture();
  auto& device = *this->device_contexts_[0];

  // Generate spirv
  auto caches = this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
      {{"RenderTests/depthTest.vert"}, {"RenderTests/depthTest.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("Test", caches);
  ASSERT_NE(material, nullptr);

  // attachment manager and textures
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        render_width,
                        render_height,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0},
                         {PixelFormat::kDepth, Framebuffer::Attachment::kDepth}});

  // renderpass and framebuffer
  auto render_pass_initial =
      resource_mgr.createRenderPass("Test",
                                    attachment_mgr.getLayout(),
                                    gfx::RenderPass::ClearBits::kAll,
                                    ImageLayout::kUndefined,
                                    ImageLayout::kAttachment);
  auto render_pass_clear_depth = resource_mgr.createRenderPass(
      "Test", attachment_mgr.getLayout(), gfx::RenderPass::ClearBits::kDepth);

  auto render_pass = resource_mgr.createRenderPass("Test", attachment_mgr.getLayout());

  ASSERT_NE(render_pass, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer(
      "Test", *render_pass, attachment_mgr, render_width, render_height, 1u);
  ASSERT_NE(framebuffer, nullptr);

  auto mesh_data = build_mesh_draw_data(
      resource_mgr, *build_uv_sphere(40, 20), "Sphere", {{"in_position"}}, *material);

  PipelineDescriptor pipeline_desc;
  pipeline_desc.setEnableDepthTest(true);
  pipeline_desc.getPushConstantRanges().insert(
      ShaderStageBits::kVertex, 0, sizeof(glm::vec3) + sizeof(float));
  auto pipeline = resource_mgr.createGraphicsPipeline(
      "Test", *material, pipeline_desc, mesh_data.pa.get());

  pipeline->create(*render_pass);

  // static uniforms
  mat4x4 view_tm;
  view_tm.perspective(render_width, render_height, 50.0f, 0.01f, 6.0f);
  material->setUniformAttribute("viewTM", view_tm);

  material->updateDescriptorSets();

  enum class ClearControlFlags { kNone, kInitial, kDepthAttachment };

  // draw lambdas to repeat draw
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();

  // Draw a single sphere
  auto draw_sphere = [&](const glm::vec3* translation, ClearControlFlags clear_flag) {
    cmd_list.setPushConstants(
        *pipeline, "DepthTest", ShaderStageBits::kVertex, translation, sizeof(glm::vec3));
    cmd_list.drawIndexed(
        *pipeline, *mesh_data.vbo, *mesh_data.ibo, mesh_data.num_indices);
  };

  // Draw set of spheres, translated along x and z (front to back). This will only
  // render properly with depth clipping
  const int kNumSpheres = 7;
  std::vector<glm::vec3> translations(kNumSpheres);
  float x = -0.8f;
  float z = -2.0f;
  for (int i = 0; i < kNumSpheres; ++i, x += 0.4f, z -= 0.25f) {
    translations[i] = glm::vec3(x, 0.0, z);
  }

  auto draw_spheres = [&](ClearControlFlags my_clear_flag, float* scale) {
    RenderPass* pass_to_use;
    switch (my_clear_flag) {
      case ClearControlFlags::kNone:
        // Don't clear anything. used for all but the first sphere in a group
        pass_to_use = render_pass.get();
        break;
      case ClearControlFlags::kInitial:
        // First renderpass of the image. Handles layout transition and clears
        // everything
        pass_to_use = render_pass_initial.get();
        break;
      case ClearControlFlags::kDepthAttachment:
        // Only clear the depth attachment
        pass_to_use = render_pass_clear_depth.get();
        break;
    }

    cmd_list.beginRenderPass(*pass_to_use, *framebuffer);
    cmd_list.setPushConstants(*pipeline,
                              "scale",
                              ShaderStageBits::kVertex,
                              scale,
                              sizeof(float),
                              sizeof(glm::vec3));
    for (int i = 0; i < kNumSpheres; ++i) {
      // only perform clearing operation on the first sphere drawn
      draw_sphere(&translations[i], (i == 0) ? my_clear_flag : ClearControlFlags::kNone);
    }
    cmd_list.endRenderPass();
  };

  // draw first set, transitions attachments and clears
  float scale1 = 0.35f;
  draw_spheres(ClearControlFlags::kInitial, &scale1);

  // draw smaller spheres at same locations, clearing depth using RenderPass::ClearBits
  // in beginRenderPass. Spheres will be culled if depth is not cleared
  float scale2 = 0.1f;
  draw_spheres(ClearControlFlags::kDepthAttachment, &scale2);

  cmd_list.flush(kTestFlushName);

  // Compare to golden image
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "depth_test"));
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kDepth, "depth_test_depth"));

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  material = nullptr;
  resource_mgr.destroyBuffer(std::move(mesh_data.vbo_wrapper));
  resource_mgr.destroyBuffer(std::move(mesh_data.ibo_wrapper));
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
  resource_mgr.destroyRenderPass(std::move(render_pass_initial));
  resource_mgr.destroyRenderPass(std::move(render_pass_clear_depth));
  // end_renderdoc_vulkan_capture();
}

//
// Subpass test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, SubpassTest) {
#else
TEST_F(RenderTest, SubpassTest) {
#endif
  // begin_renderdoc_vulkan_capture();
  auto& device = *this->device_contexts_[0];

  // When changing kNumSpheres, change the #define in subpassTest.vert too!
  static constexpr int kNumSpheres = 7;

  // Generate spirv
  auto caches = this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
      {{"RenderTests/subpassTest.vert"}, {"RenderTests/depthTest.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("SubpassTest", caches);
  ASSERT_NE(material, nullptr);

  // attachment manager and textures
  auto [attachment_mgr, textures] = build_attachments(
      resource_mgr,
      render_width,
      render_height,
      {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0},
       {PixelFormat::kDepthStencil, Framebuffer::Attachment::kDepthStencil}});

  //
  // Renderpasses
  //
  auto render_pass_1pass =
      resource_mgr.createRenderPass("SubpassTest 1-pass RenderPass",
                                    attachment_mgr.getLayout(),
                                    gfx::RenderPass::ClearBits::kNone);
  ASSERT_NE(render_pass_1pass, nullptr);

  auto render_pass_2passes = resource_mgr.createRenderPass(
      "SubpassTest 2-pass RenderPass",
      attachment_mgr.getLayout(),
      gfx::RenderPass::ClearBits::kNone,
      ImageLayout::kAttachment,
      ImageLayout::kAttachment,
      {{{Framebuffer::Attachment::kDepthStencil}, {}},
       {{Framebuffer::Attachment::kColor0, Framebuffer::Attachment::kDepthStencil}, {}}});
  ASSERT_NE(render_pass_2passes, nullptr);

  //
  // Framebuffers
  // Framebuffer / RenderPass compatibility has a subpass count dependency
  //
  auto framebuffer_1pass =
      resource_mgr.createFramebuffer("SubpassTest 1-pass Framebuffer",
                                     *render_pass_1pass,
                                     attachment_mgr,
                                     render_width,
                                     render_height,
                                     1u);
  ASSERT_NE(framebuffer_1pass, nullptr);

  auto framebuffer_2passes =
      resource_mgr.createFramebuffer("SubpassTest 2-pass Framebuffer",
                                     *render_pass_2passes,
                                     attachment_mgr,
                                     render_width,
                                     render_height,
                                     1u);
  ASSERT_NE(framebuffer_2passes, nullptr);

  // Sphere mesh draw data
  auto mesh_data = build_mesh_draw_data(
      resource_mgr, *build_uv_sphere(40, 20), "Sphere", {{"in_position"}}, *material);

  //
  // Pipelines
  // Pipelines are bound to RenderPasses and Subpasses, so we need a Pipeline
  // per subpass
  //

  //
  // 2 pass pipeline (1st pass, stencil write)
  //
  PipelineDescriptor pipeline_desc_multi_1;
  pipeline_desc_multi_1.getPushConstantRanges().insert(
      ShaderStageBits::kVertex, 0, sizeof(uint32_t));
  pipeline_desc_multi_1.setFaceCullMode(FaceCullMode::kBack);
  pipeline_desc_multi_1.setEnableDepthTest(false);
  pipeline_desc_multi_1.setEnableStencilTest(true);
  pipeline_desc_multi_1.setStencilFunc(gfx::StencilFunc::kAlways, 1, 1);
  pipeline_desc_multi_1.setStencilOp(
      gfx::StencilOp::kInvert, gfx::StencilOp::kInvert, gfx::StencilOp::kInvert);
  pipeline_desc_multi_1.setEnableColorWrites(false);
  pipeline_desc_multi_1.setEnableDepthWrites(false);

  auto pipeline_multi_pass_1 =
      resource_mgr.createGraphicsPipeline("SubpassTest subpass 1 Pipeline",
                                          *material,
                                          pipeline_desc_multi_1,
                                          mesh_data.pa.get());
  pipeline_multi_pass_1->create(*render_pass_2passes);

  //
  // 2 pass pipeline (2nd pass, color + depth + stencil test)
  //
  PipelineDescriptor pipeline_desc_multi_2;
  pipeline_desc_multi_2.setSubpassIndex(1);
  pipeline_desc_multi_2.getPushConstantRanges().insert(
      ShaderStageBits::kVertex, 0, sizeof(uint32_t));
  pipeline_desc_multi_1.setFaceCullMode(FaceCullMode::kBack);
  pipeline_desc_multi_2.setEnableDepthTest(true);
  pipeline_desc_multi_2.setEnableStencilTest(true);
  pipeline_desc_multi_2.setStencilFunc(gfx::StencilFunc::kEqual, 1, 1);
  pipeline_desc_multi_2.setStencilOp(
      gfx::StencilOp::kKeep, gfx::StencilOp::kKeep, gfx::StencilOp::kKeep);
  pipeline_desc_multi_2.setEnableColorWrites(true);
  pipeline_desc_multi_2.setEnableDepthWrites(true);

  auto pipeline_multi_pass_2 =
      resource_mgr.createGraphicsPipeline("SubpassTest subpass 2 Pipeline",
                                          *material,
                                          pipeline_desc_multi_2,
                                          mesh_data.pa.get());
  pipeline_multi_pass_2->create(*render_pass_2passes);

  //
  // 1 pass pipeline (color + depth + stencil test)
  //
  PipelineDescriptor pipeline_desc_single;
  pipeline_desc_single.getPushConstantRanges().insert(
      ShaderStageBits::kVertex, 0, sizeof(uint32_t));
  pipeline_desc_multi_1.setFaceCullMode(FaceCullMode::kBack);
  pipeline_desc_single.setEnableDepthTest(true);
  pipeline_desc_single.setEnableStencilTest(true);
  pipeline_desc_single.setStencilFunc(gfx::StencilFunc::kNotEqual, 1, 1);
  pipeline_desc_single.setStencilOp(
      gfx::StencilOp::kKeep, gfx::StencilOp::kKeep, gfx::StencilOp::kKeep);
  pipeline_desc_single.setEnableColorWrites(true);
  pipeline_desc_single.setEnableDepthWrites(true);

  auto pipeline_single_pass =
      resource_mgr.createGraphicsPipeline("SubpassTest single pass Pipeline",
                                          *material,
                                          pipeline_desc_single,
                                          mesh_data.pa.get());
  pipeline_single_pass->create(*render_pass_1pass);

  //
  // Set static uniforms and update descriptors
  //
  mat4x4 view_tm;
  view_tm.perspective(render_width, render_height, 50.0f, 0.01f, 6.0f);
  material->setUniformAttribute("viewTM", view_tm);

  material->updateDescriptorSets();

  // CommandList
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();

  // Test transition image layouts to kAttachment without using a RenderPass. Doing
  // this in the first RenderPass is most efficient, this just provides additional
  // API test coverage
  // BUG: The flush is required, otherwise validation fails complaining that all the
  // images are still in undefined layout when the first renderpass begins
  cmd_list.transitionFramebufferLayout(*framebuffer_1pass, ImageLayout::kAttachment)
      .clearTexture(*textures[0])
      .clearTexture(*textures[1])
      .flush(kTestFlushName);

  //
  // Fill the sphere_positions uniform array
  //
  std::array<float, kNumSpheres * 4> sphere_positions;
  {
    float x = -0.8f;
    float y = 0.0f;
    float z = -2.0f;
    int array_idx = 0;
    for (int i = 0; i < kNumSpheres; ++i, x += 0.4f, z -= 0.25f) {
      sphere_positions[array_idx++] = x;
      sphere_positions[array_idx++] = y;
      sphere_positions[array_idx++] = z;
      sphere_positions[array_idx++] = 1.0f;
    }
  }
  material->setUniformAttribute("objPositions", sphere_positions);

  //
  // Draw the spheres array with the given Pipeline
  //
  auto draw_spheres = [&](Pipeline& draw_pipeline) {
    for (int i = 0; i < kNumSpheres; ++i) {
      cmd_list.setPushConstantUInt32(
          draw_pipeline, "object_index", ShaderStageBits::kVertex, i);
      cmd_list.drawIndexed(
          draw_pipeline, *mesh_data.vbo, *mesh_data.ibo, mesh_data.num_indices);
    }
  };

  //
  // Draw the spheres using the 1 pass or 2 pass renderpass / pipeline combo
  //
  enum class RenderPassFlags { kOnePass, kTwoPass };
  auto draw_render_pass = [&](RenderPassFlags pass_flag) {
    if (pass_flag == RenderPassFlags::kTwoPass) {
      cmd_list.beginRenderPass(*render_pass_2passes, *framebuffer_2passes);
      draw_spheres(*pipeline_multi_pass_1);
      cmd_list.nextSubpass();
      draw_spheres(*pipeline_multi_pass_2);
    } else {  // RenderPassFlags::kOnePass
      cmd_list.beginRenderPass(*render_pass_1pass, *framebuffer_1pass);
      draw_spheres(*pipeline_single_pass);
    }
    cmd_list.endRenderPass().flush(kTestFlushName);
  };

  //
  // Do the actual drawing
  //

  // Draw small spheres in 2 subpasses. First is just a stencil pass
  // second subpass redraws with color and depth enabled
  material->setUniformAttribute("scale", 0.1f);
  draw_render_pass(RenderPassFlags::kTwoPass);

  // Draw large spheres inverting the stencil test so they don't overdraw
  // the small spheres
  material->setUniformAttribute("scale", 0.35f);
  draw_render_pass(RenderPassFlags::kOnePass);

  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer_1pass, Framebuffer::Attachment::kColor0, "subpass_test"));

  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer_1pass, Framebuffer::Attachment::kDepthStencil, "subpass_test_depth"));

  //
  // destroy resources
  //
  resource_mgr.destroyPipeline(std::move(pipeline_single_pass));
  resource_mgr.destroyPipeline(std::move(pipeline_multi_pass_1));
  resource_mgr.destroyPipeline(std::move(pipeline_multi_pass_2));
  material = nullptr;
  resource_mgr.destroyBuffer(std::move(mesh_data.vbo_wrapper));
  resource_mgr.destroyBuffer(std::move(mesh_data.ibo_wrapper));
  resource_mgr.destroyFramebuffer(std::move(framebuffer_1pass));
  resource_mgr.destroyFramebuffer(std::move(framebuffer_2passes));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass_2passes));
  resource_mgr.destroyRenderPass(std::move(render_pass_1pass));
  // end_renderdoc_vulkan_capture();
}

//
// CanUseEmptyFramebufferTest
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, CanUseEmptyFramebufferTest) {
#else
TEST_F(RenderTest, CanUseEmptyFramebufferTest) {
#endif
  auto& device = *this->device_contexts_[0];

  auto& resource_mgr = device.getResourceManager();

  // material
  auto shader_caches =
      this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
          {{"DriverTests/fullScreenTriangle.vert"},
           {"RenderTests/emptyFramebufferTest.frag"}});
  ASSERT_TRUE(validate_shader_caches(shader_caches));

  auto material = resource_mgr.createMaterial("EmptyFramebufferTest", shader_caches);
  ASSERT_NE(material, nullptr);

  // storage texture
  auto storage_image = resource_mgr.createTexture(
      "EmptyFramebufferTest",
      render_width,
      render_height,
      1,
      PixelFormat::kR32UI,
      1,
      false,
      ImageUsageBits::kStorageBit,
      get_default_sampler_state_for_format(PixelFormat::kR32UI));
  ASSERT_NE(storage_image, nullptr);

  // Clear pixels and implicit transition to general layout
  storage_image->clearPixels();

  material->setImageLoadStoreAttribute("pixelCounter", *storage_image);
  material->updateDescriptorSets();

  // Create an empty AttachmentManager, RenderPass, and Framebuffer
  AttachmentManager attachment_mgr;
  auto render_pass =
      resource_mgr.createRenderPass("EmptyFramebufferTest", attachment_mgr.getLayout());
  ASSERT_NE(render_pass, nullptr);

  // Framebuffer still requires a size and sample count to control rasterization
  auto framebuffer = resource_mgr.createFramebuffer("EmptyFramebufferTest",
                                                    *render_pass,
                                                    attachment_mgr,
                                                    render_width,
                                                    render_height,
                                                    1);
  ASSERT_NE(framebuffer, nullptr);

  // Create a pipeline
  PipelineDescriptor pipeline_desc;
  auto pipeline = resource_mgr.createGraphicsPipeline(
      "EmptyFramebufferTest", *material, pipeline_desc);
  ASSERT_NE(pipeline, nullptr);
  ASSERT_NO_THROW(pipeline->create(*render_pass));

  // Render a fullscreen triangle that should increment each pixel once in the fragment
  // shader
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();
  cmd_list.beginRenderPass(*render_pass, *framebuffer)
      .drawFullscreen(*pipeline)
      .endRenderPass()
      .flush(kTestFlushName);

  // Check that all pixels == 1
  uint32_t num_pixels = render_width * render_height;
  std::vector<uint32_t> pixels(num_pixels);
  storage_image->getPixels(
      render_width, render_height, 1, PixelFormat::kR32UI, pixels.data(), num_pixels * 4);
  uint32_t failed_pixel_count = 0u;
  for (auto pixel : pixels) {
    if (pixel != 1u) {
      failed_pixel_count++;
    }
  }
  EXPECT_EQ(failed_pixel_count, 0u);

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  resource_mgr.destroyRenderPass(std::move(render_pass));
  material = nullptr;
  resource_mgr.destroyTexture(std::move(storage_image));
}

//
// ImageLoadStore test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, ImageLoadStoreTest) {
#else
TEST_F(RenderTest, ImageLoadStoreTest) {
#endif
  // begin_renderdoc_vulkan_capture();
  auto& device = *this->device_contexts_[0];

  static constexpr uint32_t kRenderWidth = 640;
  static constexpr uint32_t kRenderHeight = 640;

  // Generate spirv
  auto const& shader_mgr = this->gfx_context_->getShaderManager();
  auto caches_draw_pass = shader_mgr.createCacheVectorFromTemplate(
      {{"RenderTests/loadStoreTest_draw.vert"}, {"RenderTests/loadStoreTest_draw.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches_draw_pass));

  auto caches_extents_pass = shader_mgr.createCacheVectorFromTemplate(
      {{"DriverTests/fullScreenTriangle.vert"},
       {"RenderTests/loadStoreTest_extents.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches_extents_pass));

  auto caches_stddev_pass = shader_mgr.createCacheVectorFromTemplate(
      {{"DriverTests/fullScreenTriangle.vert"},
       {"RenderTests/loadStoreTest_stddev.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches_stddev_pass));

  auto caches_color_pass = shader_mgr.createCacheVectorFromTemplate(
      {{"DriverTests/fullScreenTriangle.vert"},
       {"RenderTests/loadStoreTest_color.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches_color_pass));

  auto& resource_mgr = device.getResourceManager();

  // materials
  auto material_draw_pass =
      resource_mgr.createMaterial("ImageLoadStoreTest draw", caches_draw_pass);
  ASSERT_NE(material_draw_pass, nullptr);

  auto material_extents_pass =
      resource_mgr.createMaterial("ImageLoadStoreTest extents", caches_extents_pass);
  ASSERT_NE(material_extents_pass, nullptr);

  auto material_stddev_pass =
      resource_mgr.createMaterial("ImageLoadStoreTest stddev", caches_stddev_pass);
  ASSERT_NE(material_stddev_pass, nullptr);

  auto material_color_pass =
      resource_mgr.createMaterial("ImageLoadStoreTest color", caches_color_pass);
  ASSERT_NE(material_color_pass, nullptr);

  // pixel counter image
  auto pixel_counter_image = resource_mgr.createTexture(
      "ImageLoadStoreTest",
      kRenderWidth,
      kRenderHeight,
      1,
      PixelFormat::kR32UI,
      1,
      false,
      ImageUsageBits::kStorageBit,
      get_default_sampler_state_for_format(PixelFormat::kR32UI));
  ASSERT_NE(pixel_counter_image, nullptr);

  // image stats struct
  struct ImageStats {
    uint64_t totalNonZeroCount;
    uint64_t totalSqrDiff;
    uint32_t minCount;
    uint32_t maxCount;
    uint32_t numNonZeroCount;
  };

  // image stats SSBO
  auto image_stats_ssbo_buffer = resource_mgr.createHostVisibleBuffer(
      "ImageLoadStoreTest stats",
      {BufferType::kUnspecified, sizeof(ImageStats), BufferUsageBits::kStorageBufferBit});
  ASSERT_NE(image_stats_ssbo_buffer, nullptr);
  auto& image_stats_ssbo = image_stats_ssbo_buffer->getSourceBufferWrapper();

  // Set attributes and update descriptor sets
  material_draw_pass->setImageLoadStoreAttribute("pixelCounter", *pixel_counter_image);
  material_draw_pass->updateDescriptorSets();

  material_extents_pass->setImageLoadStoreAttribute("pixelCounter", *pixel_counter_image);
  material_extents_pass->bindShaderStorageBufferToBlock("IMAGE_STATS_SSBO",
                                                        image_stats_ssbo);
  material_extents_pass->updateDescriptorSets();

  material_stddev_pass->setImageLoadStoreAttribute("pixelCounter", *pixel_counter_image);
  material_stddev_pass->bindShaderStorageBufferToBlock("IMAGE_STATS_SSBO",
                                                       image_stats_ssbo);
  material_stddev_pass->updateDescriptorSets();

  material_color_pass->setImageLoadStoreAttribute("pixelCounter", *pixel_counter_image);
  material_color_pass->bindShaderStorageBufferToBlock("IMAGE_STATS_SSBO",
                                                      image_stats_ssbo);
  material_color_pass->updateDescriptorSets();

  // attachment manager and textures for final output image
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        kRenderWidth,
                        kRenderHeight,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0},
                         {PixelFormat::kRGBA8, Framebuffer::Attachment::kColor1}});

  // Renderpass and framebuffer
  // There are 4 subpasses:
  // - draw which draws the point primitives filling the accumulation storage image
  // - extents reads the storage image and generates reduction stats (min, max, etc)
  // - stddev computes the mean and variance using the accumulation and extents images
  // - color generates 2 color outputs, 1 encoding the basic density, the other outputs
  //   standard dev (sqrt of the variance computed by the stddev pass)
  enum { kDrawPass, kExtentsPass, kStdDevPass, kColorPass };
  std::vector<SubpassDescriptor> subpasses(4);
  subpasses[kDrawPass].dependencies = SubpassDependencyBits::kFragmentShaderWrite;
  subpasses[kExtentsPass].dependencies = SubpassDependencyBits::kFragmentShaderRead |
                                         SubpassDependencyBits::kFragmentShaderWrite;
  subpasses[kStdDevPass].dependencies = SubpassDependencyBits::kFragmentShaderRead |
                                        SubpassDependencyBits::kFragmentShaderWrite;
  subpasses[kColorPass].attachments = attachment_mgr.getAllAttachmentsSet();
  subpasses[kColorPass].dependencies = SubpassDependencyBits::kFragmentShaderRead;

  auto render_pass = resource_mgr.createRenderPass("ImageLoadStoreTest",
                                                   attachment_mgr.getLayout(),
                                                   gfx::RenderPass::ClearBits::kAll,
                                                   ImageLayout::kUndefined,
                                                   ImageLayout::kAttachment,
                                                   subpasses);
  ASSERT_NE(render_pass, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer("ImageLoadStoreTest",
                                                    *render_pass,
                                                    attachment_mgr,
                                                    kRenderWidth,
                                                    kRenderHeight,
                                                    1u);
  ASSERT_NE(framebuffer, nullptr);

  // vertex buffer, layout, and attr map
  auto buffer_layout = std::make_shared<InterleavedBufferLayout>();
  ASSERT_NE(buffer_layout, nullptr);
  buffer_layout->addAttribute("in_position", BufferAttrType::kVec2f);
  buffer_layout->addAttribute("in_pointSize", BufferAttrType::kFloat);

  // Generate pseudo random radial distribution of vertices
  static constexpr uint32_t kNumPoints = 500000;
  std::vector<float> vertex_data(kNumPoints * 3);

  std::mt19937 theta_gen(1);
  std::mt19937 radius_gen(2);
  std::uniform_real_distribution<float> pos_dis(0.0f, 1.0f);
  std::uniform_real_distribution<float> radius_dis(0.1f, 1.0f);
  uint32_t index = 0u;
  for (uint32_t i = 0; i < kNumPoints; ++i) {
    float theta = pos_dis(theta_gen) * 6.28318530718f;
    float r = radius_dis(radius_gen);
    vertex_data[index++] = r * cosf(theta);
    vertex_data[index++] = r * sinf(theta);
    vertex_data[index++] = 30.0f;  // size
  }

  auto vertex_buffer_wrapper =
      resource_mgr.createBuffer("ImageLoadStoreTest",
                                {BufferType::kVertexBuffer,
                                 vertex_data.size() * sizeof(float),
                                 BufferUsageBits::kLayoutBufferBit});
  ASSERT_NE(vertex_buffer_wrapper, nullptr);

  auto* vertex_buffer = static_cast<VertexBuffer*>(vertex_buffer_wrapper.get());
  vertex_buffer->updateSubDataWithLayout(
      vertex_data.data(), vertex_buffer_wrapper->getNumBytes(), 0, buffer_layout);

  PrimitiveAssemblyAttrInfo attr_info = {
      {vertex_buffer, buffer_layout},
      {{"in_position", "in_position"}, {"in_pointSize", "in_pointSize"}}};

  // Pipelines
  // Point draw pass
  auto primitive_assembly_draw_pass =
      resource_mgr.createPrimitiveAssembly("ImageLoadStoreTest draw",
                                           PrimitiveTopology::kPointList,
                                           *material_draw_pass,
                                           attr_info);
  PipelineDescriptor pipeline_desc_draw_pass;
  pipeline_desc_draw_pass.setSubpassIndex(kDrawPass);
  auto pipeline_draw_pass =
      resource_mgr.createGraphicsPipeline("ImageLoadStoreTest draw",
                                          *material_draw_pass,
                                          pipeline_desc_draw_pass,
                                          primitive_assembly_draw_pass.get());
  ASSERT_NE(pipeline_draw_pass, nullptr);

  pipeline_draw_pass->create(*render_pass);

  // extents pass
  PipelineDescriptor pipeline_desc_extents_pass;
  pipeline_desc_extents_pass.setSubpassIndex(kExtentsPass);
  auto pipeline_extents_pass = resource_mgr.createGraphicsPipeline(
      "ImageLoadStoreTest extents", *material_extents_pass, pipeline_desc_extents_pass);
  ASSERT_NE(pipeline_extents_pass, nullptr);
  pipeline_extents_pass->create(*render_pass);

  // stddev pass
  PipelineDescriptor pipeline_desc_stddev_pass;
  pipeline_desc_stddev_pass.setSubpassIndex(kStdDevPass);
  auto pipeline_stddev_pass = resource_mgr.createGraphicsPipeline(
      "ImageLoadStoreTest stddev", *material_stddev_pass, pipeline_desc_stddev_pass);
  ASSERT_NE(pipeline_stddev_pass, nullptr);
  pipeline_stddev_pass->create(*render_pass);

  // color pass
  PipelineDescriptor pipeline_desc_color_pass;
  pipeline_desc_color_pass.setSubpassIndex(kColorPass);
  auto pipeline_color_pass = resource_mgr.createGraphicsPipeline(
      "ImageLoadStoreTest color", *material_color_pass, pipeline_desc_color_pass);
  ASSERT_NE(pipeline_color_pass, nullptr);
  pipeline_color_pass->create(*render_pass);

  // render via command list
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, kRenderWidth, kRenderHeight);
  auto& cmd_list = device.getCommandList();

  // test layout transition commands
  cmd_list.imageMemoryBarrier(
      *pixel_counter_image, ImageMemoryBarrierType::kImageLayout, ImageLayout::kGeneral);

  // Loop to ensure memory barriers work correctly in multiple renders
  static constexpr int kLoopCount = 10;

  for (int i = 0; i < kLoopCount; ++i) {
    // Initialize the storage image and initialize extents
    cmd_list.clearTexture(*pixel_counter_image);

    // Initialize image stats
    ImageStats* image_stats{};
    image_stats_ssbo_buffer->map((void**)&image_stats);
    EXPECT_NE(nullptr, image_stats);
    image_stats->totalNonZeroCount = 0ull;
    image_stats->totalSqrDiff = 0ull;
    image_stats->minCount = std::numeric_limits<uint32_t>::max();
    image_stats->maxCount = std::numeric_limits<uint32_t>::min();
    image_stats->numNonZeroCount = 0u;
    image_stats_ssbo_buffer->unmap();

    // Draw all the subpasses
    cmd_list.beginRenderPass(*render_pass, *framebuffer)
        .drawVertices(*pipeline_draw_pass, *vertex_buffer, kNumPoints)
        .nextSubpass()
        .drawFullscreen(*pipeline_extents_pass)
        .nextSubpass()
        .drawFullscreen(*pipeline_stddev_pass)
        .nextSubpass()
        .drawFullscreen(*pipeline_color_pass)
        .endRenderPass()
        .flush(kTestFlushName);

    // Compare to golden images
    EXPECT_TRUE(this->golden_image_->compare(*framebuffer,
                                             Framebuffer::Attachment::kColor0,
                                             "load_store_test_density",
                                             false,
                                             8u,
                                             6u));
    EXPECT_TRUE(this->golden_image_->compare(*framebuffer,
                                             Framebuffer::Attachment::kColor1,
                                             "load_store_test_stddev",
                                             false,
                                             2u,
                                             1u));

    // Fetch and log image stats (first time only)
    if (i == 0) {
      image_stats_ssbo_buffer->map((void**)&image_stats);
      EXPECT_NE(nullptr, image_stats);
#if SHOW_IMAGE_LOAD_STORE_STATS
      std::cout << "minCount          " << image_stats->minCount << std::endl;
      std::cout << "maxCount          " << image_stats->maxCount << std::endl;
      std::cout << "totalNonZeroCount " << image_stats->totalNonZeroCount << std::endl;
      std::cout << "numNonZeroCount   " << image_stats->numNonZeroCount << std::endl;
      std::cout << "totalSqrDiff      " << image_stats->totalSqrDiff << std::endl;
#endif
      // just check these three, as the large totals are platform-variant
      EXPECT_EQ(image_stats->minCount, 1u);
      EXPECT_EQ(image_stats->maxCount, 3742u);
      EXPECT_EQ(image_stats->numNonZeroCount, 341189u);
      image_stats_ssbo_buffer->unmap();
    }
  }

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline_draw_pass));
  resource_mgr.destroyPipeline(std::move(pipeline_extents_pass));
  resource_mgr.destroyPipeline(std::move(pipeline_stddev_pass));
  resource_mgr.destroyPipeline(std::move(pipeline_color_pass));
  material_draw_pass = nullptr;
  material_extents_pass = nullptr;
  material_stddev_pass = nullptr;
  material_color_pass = nullptr;
  resource_mgr.destroyBuffer(std::move(vertex_buffer_wrapper));
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
  resource_mgr.destroyTexture(std::move(pixel_counter_image));
  resource_mgr.destroyHostVisibleBuffer(std::move(image_stats_ssbo_buffer));
  // end_renderdoc_vulkan_capture();
}

//
// Fragment Shader Interlock Test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, FragmentShaderInterlockTest) {
#else
TEST_F(RenderTest, FragmentShaderInterlockTest) {
#endif
  static constexpr std::string_view kTestName = "FragmentShaderInterlockTest";

  auto& device = *this->device_contexts_[0];
  if (!any_bits_set(device.getCapabilityBits() &
                    DeviceCapabilityBits::kFragmentShaderPixelInterlock)) {
    GTEST_SKIP() << "Device does not support fragment shader interlock";
  }
  if (!any_bits_set(device.getCapabilityBits() & DeviceCapabilityBits::kRayQuery)) {
    GTEST_SKIP()
        << "Fragment shader interlock supported but unstable on Pascal based GPUs";
  }

  static constexpr uint32_t kRenderWidth = 400;
  static constexpr uint32_t kRenderHeight = 400;

  // Generate spirv
  auto caches_draw_pass =
      this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
          {{"RenderTests/fragmentShaderInterlockTest.vert"},
           {"RenderTests/fragmentShaderInterlockTest.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches_draw_pass));

  auto& resource_mgr = device.getResourceManager();

  // Material
  auto material = resource_mgr.createMaterial(kTestName, caches_draw_pass);
  ASSERT_NE(material, nullptr);

  auto output_texture = resource_mgr.createTexture(kTestName,
                                                   kRenderWidth,
                                                   kRenderHeight,
                                                   1,
                                                   PixelFormat::kRGBA8,
                                                   1,
                                                   false,
                                                   ImageUsageBits::kStorageBit,
                                                   default_texture_sampler_state_nearest);

  static gfx::AttachmentManager empty_attachment_mgr;
  auto render_pass =
      resource_mgr.createRenderPass(kTestName, empty_attachment_mgr.getLayout());
  auto framebuffer = resource_mgr.createFramebuffer(
      kTestName, *render_pass, empty_attachment_mgr, kRenderWidth, kRenderHeight, 1);

  // vertex buffer, layout, and attr map
  auto buffer_layout = std::make_shared<InterleavedBufferLayout>();
  ASSERT_NE(buffer_layout, nullptr);
  buffer_layout->addAttribute("in_position", BufferAttrType::kVec2f);
  buffer_layout->addAttribute("in_key", BufferAttrType::kFloat);

  static constexpr uint32_t kNumPoints = 1000;

  // Generate spiral of vertices to use for points
  std::vector<float> vertex_data(kNumPoints * 3);

  uint32_t index = 0u;
  for (uint32_t i = 0; i < kNumPoints; ++i) {
    float mu = static_cast<float>(i) / static_cast<float>(kNumPoints);
    float theta = mu * 100.0f;
    vertex_data[index++] = mu * cosf(theta);
    vertex_data[index++] = mu * sinf(theta);
    vertex_data[index++] = mu;
  }

  auto vertex_buffer_wrapper =
      resource_mgr.createBuffer(kTestName,
                                {BufferType::kVertexBuffer,
                                 vertex_data.size() * sizeof(float),
                                 BufferUsageBits::kLayoutBufferBit});
  CHECK(vertex_buffer_wrapper);

  auto* vertex_buffer = static_cast<VertexBuffer*>(vertex_buffer_wrapper.get());
  vertex_buffer->updateSubDataWithLayout(
      vertex_data.data(), vertex_buffer_wrapper->getNumBytes(), 0, buffer_layout);

  PrimitiveAssemblyAttrInfo attr_info = {
      {vertex_buffer, buffer_layout},
      {{"in_position", "in_position"}, {"in_key", "in_key"}}};

  // Pipeline
  auto primitive_assembly = resource_mgr.createPrimitiveAssembly(
      kTestName, PrimitiveTopology::kPointList, *material, attr_info);
  PipelineDescriptor pipeline_desc;

  auto pipeline = resource_mgr.createGraphicsPipeline(
      kTestName, *material, pipeline_desc, primitive_assembly.get());
  ASSERT_NE(pipeline, nullptr);

  pipeline->create(*render_pass);

  enum Timestamps { kTopOfPipe, kClearTexture, kDraw, kNumTimestamps };

  // Query Pools
  auto timestamps_query_pool =
      resource_mgr.createTimestampQueryPool(kTestName, kNumTimestamps);
  auto statistics_query_pool = resource_mgr.createPipelineStatisticsQueryPool(
      kTestName, Pipeline::Type::kGraphics);
  auto occlusion_query_pool = resource_mgr.createOcclusionQueryPool(kTestName);

  // Draw
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, kRenderWidth, kRenderHeight);
  material->setImageLoadStoreAttribute("output_image", *output_texture);
  material->updateDescriptorSets();

  auto start_time = timer_start();
  device.getCommandList()
      .resetQueryPool(*timestamps_query_pool)
      .resetQueryPool(*statistics_query_pool)
      .resetQueryPool(*occlusion_query_pool)
      .writeTimestamp(
          *timestamps_query_pool, PipelineStageBits::kTopOfPipeBit, kTopOfPipe)
      .clearTexture(*output_texture, ImageLayout::kGeneral)
      .writeTimestamp(
          *timestamps_query_pool, PipelineStageBits::kTransferBit, kClearTexture)
      .beginQuery(*statistics_query_pool)
      .beginQuery(*occlusion_query_pool)
      .beginRenderPass(*render_pass, *framebuffer)
      .drawVertices(*pipeline, *vertex_buffer, kNumPoints)
      .writeTimestamp(*timestamps_query_pool, PipelineStageBits::kBottomOfPipeBit, kDraw)
      .endRenderPass()
      .endQuery(*statistics_query_pool)
      .endQuery(*occlusion_query_pool)
      .flush(kTestName);
  std::cout << "Command list time: " << timer_stop_microseconds(start_time) << std::endl;

  auto timestamps = timestamps_query_pool->getTimestampResults(
      0, kNumTimestamps, QueryPool::GetResultMode::kWithAvailability);
  std::cout << "Timestamps:\n";
  for (auto timestamp : timestamps) {
    std::cout << timestamp << "\n";
  }
  std::cout << std::endl;
  auto clear_time = timestamps_query_pool->timestampToMicroseconds(
      timestamps[kClearTexture * 2] - timestamps[kTopOfPipe * 2]);
  auto draw_time = timestamps_query_pool->timestampToMicroseconds(
      timestamps[kDraw * 2] - timestamps[kClearTexture * 2]);
  std::cout << "Clear time: " << clear_time << " (us)" << std::endl;
  std::cout << "Draw time: " << draw_time << "(us)" << std::endl;

  auto pipeline_statistics = statistics_query_pool->getGraphicsPipelineStatistics(
      QueryPool::GetResultMode::kWithAvailability);
  std::cout << "Pipeline Statistics:" << std::endl;
  std::cout << pipeline_statistics << std::endl;

  auto occlusion_statistics = occlusion_query_pool->getOcclusionStatistics(
      QueryPool::GetResultMode::kWithAvailability);
  std::cout << "Occlusion:" << std::endl;
  std::cout << "Num Samples: " << occlusion_statistics.num_samples << std::endl;
  std::cout << "Availability: " << occlusion_statistics.availability << std::endl;

  EXPECT_TRUE(this->golden_image_->compare(*output_texture, "fragment_shader_interlock"));

  resource_mgr.destroyQueryPool(std::move(timestamps_query_pool));
  resource_mgr.destroyQueryPool(std::move(statistics_query_pool));
  resource_mgr.destroyQueryPool(std::move(occlusion_query_pool));
  resource_mgr.destroyPipeline(std::move(pipeline));
  resource_mgr.destroyBuffer(std::move(vertex_buffer_wrapper));
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  resource_mgr.destroyTexture(std::move(output_texture));
  resource_mgr.destroyRenderPass(std::move(render_pass));
}

//
// PBRMaterialManager and LightManager test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, PBRMaterialTest) {
#else
TEST_F(RenderTest, PBRMaterialTest) {
#endif
  const uint32_t kRenderWidth = 512;
  const uint32_t kRenderHeight = 512;
  auto& device = *this->device_contexts_[0];
  auto& resource_mgr = device.getResourceManager();
  auto& shader_mgr = resource_mgr.getShaderManager();

  //
  // Init instances and material properties
  //

  const int kNumRows = 10;
  const int kNumColumns = 10;
  const int kNumInstances = kNumRows * kNumColumns;
  const float kInstanceScale = 0.075f;
  std::vector<glm::vec4> instances_host_buffer(kNumInstances);
  PBRMaterialManager cook_torrance_materials;
  PBRMaterialManager blinn_phong_materials;
  std::vector<PBRMaterialDescriptor> cook_torrance_descs;

  const glm::vec4 cook_torrance_albedo{0.5f, 0.8f, 0.4f, 1.0f};
  const glm::vec4 blinn_phong_albedo{0.1f, 0.6f, 0.1f, 1.0f};
  const float x_step = 2.f / (kNumColumns - 1);
  const float y_step = 2.f / (kNumRows - 1);
  const float roughness_step = 1.f / (kNumColumns - 1);
  const float metallic_step = 1.f / (kNumRows - 1);
  const float glossiness_step = 40.f / (kNumColumns - 1);
  const float spec_strength_step = 1.5f / (kNumRows - 1);
  int vi = 0;
  float roughness = 0.0f;
  float glossiness = 1.0f;
  for (float y = 1.0f; y >= -1.0f;
       y -= y_step, roughness += roughness_step, glossiness += glossiness_step) {
    float metallic = 0.0f;
    float spec_strength = 0.0f;
    for (float x = -1.0f; x <= 1.0f;
         x += x_step, metallic += metallic_step, spec_strength += spec_strength_step) {
      instances_host_buffer[vi] = glm::vec4{x, y, 0.0f, kInstanceScale};
      cook_torrance_descs.push_back(cook_torrance_materials.addCookTorranceMaterial(
          PBRMaterialDescriptor::ColorSource::kConstant,
          cook_torrance_albedo,
          1.0f,
          roughness,
          metallic));
      blinn_phong_materials.addBlinnPhongMaterial(
          PBRMaterialDescriptor::ColorSource::kConstant,
          blinn_phong_albedo,
          1.0f,
          glossiness,
          spec_strength);
      vi++;
    }
  }

  uint64_t buffer_size = instances_host_buffer.size() * sizeof(glm::vec4);

  auto instances_ssbo = resource_mgr.createBuffer(
      "Instances",
      {BufferType::kUnspecified, buffer_size, BufferUsageBits::kStorageBufferBit});

  instances_ssbo->updateSubData(instances_host_buffer.data(), buffer_size, 0);

  // Model matrices
  struct ModelMatrices {
    glm::mat4 model_tm{1};
    glm::mat4 normal_tm{1};
  };

  ModelMatrices model_matrices;
  auto model_matrices_ubo =
      resource_mgr.createBuffer("Model Matrices UBO",
                                {gfx::BufferType::kUnspecified,
                                 sizeof(ModelMatrices),
                                 gfx::BufferUsageBits::kUniformBufferBit,
                                 gfx::BufferAccessType::kHostVisible});
  model_matrices_ubo->updateSubData(&model_matrices, sizeof(ModelMatrices), 0);

  // Camera
  auto camera =
      std::make_unique<Camera>(Camera::Projection::kOrthographic, Camera::Type::kLookAt);
  camera->setClip(10.f, 0.f);
  camera->setPosition(glm::vec3{0.0f, 0.0f, 2.5f});
  camera->setOrthoParams(-glm::vec2{1.25f - (kInstanceScale * 2.0f)},
                         glm::vec2{1.25f - (kInstanceScale * 2.0f)},
                         10.f,
                         0.f);

  auto projection_ubo = Camera::createBuffer(resource_mgr);
  camera->updateBufferData(*projection_ubo);

  LightManager lightmgr;
  lightmgr.addParallelLight(
      glm::normalize(glm::vec3{0.5, -0.25, 0.5}), glm::vec3{1.5, 1.25, 1.0}, 1.0);
  lightmgr.addPointLight({-15, -35, 0}, {0.2, 0.2, 0.9}, 1.0, false);
  // Save the LightDesc to test updating a light
  // Test move construction into a unique_ptr (default constructor is deleted)
  std::unique_ptr<LightDescriptor> point_light_desc;
  point_light_desc = std::make_unique<LightDescriptor>(
      lightmgr.addPointLight({-5, 35, -5}, {0.8, 0.2, 0.0}, 2000.0, true));

  auto light_data_ssbo = lightmgr.createBuffer(resource_mgr);
  lightmgr.updateBufferData(*light_data_ssbo);

  //
  // Materials
  //
  auto builders = shader_mgr.createBuilderVector(
      {{"Shading/shadingBase.vert"}, {"Shading/shadingMain.frag"}});
  builders[0]->appendTemplate("Shading/shadingMain.vert");
  builders[0]->setExternalUniformBuffers(
      {"MODEL_MATRICES_UBO_TYPE", "PROJECTION_UBO_TYPE"});

  auto caches = shader_mgr.createCacheVector(std::move(builders), true);
  auto material = resource_mgr.createMaterial("Material", caches);

  material->bindShaderStorageBufferToBlock("INSTANCE_DATA_SSBO", *instances_ssbo);
  material->bindExternalUniformBufferToBlock("PROJECTION_UBO_TYPE", *projection_ubo);
  material->bindExternalUniformBufferToBlock("MODEL_MATRICES_UBO_TYPE",
                                             *model_matrices_ubo);

  auto material_ssbo =
      cook_torrance_materials.createBuffer(resource_mgr, BufferAccessType::kDeviceLocal);
  cook_torrance_materials.bindToMaterial(*material, *material_ssbo);

  lightmgr.bindToMaterial(*material, *light_data_ssbo);

  // RenderPass and Framebuffer
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        kRenderWidth,
                        kRenderHeight,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

  auto render_pass = resource_mgr.createRenderPass("RenderPass",
                                                   attachment_mgr.getLayout(),
                                                   gfx::RenderPass::ClearBits::kAll,
                                                   ImageLayout::kUndefined,
                                                   ImageLayout::kAttachment);

  auto framebuffer = resource_mgr.createFramebuffer(
      "Framebuffer", *render_pass, attachment_mgr, kRenderWidth, kRenderHeight, 1);

  // Mesh
  std::vector<std::string> material_attrs = {{"in_position"}, {"in_normal"}};
  auto mesh_data = build_mesh_draw_data(
      resource_mgr, *build_uv_sphere(40, 20, true), "Sphere", material_attrs, *material);

  // Pipeline
  PipelineDescriptor pipeline_desc;
  pipeline_desc.setFaceCullMode(FaceCullMode::kBack);
  auto pipeline = resource_mgr.createGraphicsPipeline(
      "Shaded", *material, pipeline_desc, mesh_data.pa.get());
  pipeline->create(*render_pass);

  // Draw lambda
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, kRenderWidth, kRenderHeight);
  material->updateDescriptorSets();

  auto draw_spheres = [&]() {
    device.getCommandList()
        .beginRenderPass(*render_pass, *framebuffer)
        .drawIndexed(*pipeline,
                     *mesh_data.vbo,
                     *mesh_data.ibo,
                     mesh_data.num_indices,
                     0,
                     0,
                     kNumInstances)
        .endRenderPass()
        .flush("Test");
  };

  // Draw Cook-Torrance grid
  cook_torrance_materials.updateBufferData(*material_ssbo);
  draw_spheres();
  // 470 drivers render 1 pixel differently than subsequent drivers so add the
  // minimal tolerance
  EXPECT_TRUE(this->golden_image_->compare(*framebuffer,
                                           Framebuffer::Attachment::kColor0,
                                           "pbr_cook_torrance_test",
                                           false,
                                           1,
                                           1));

  // Change Cook-Torrance materials to Constant shaded and modify albedo
  float hue_step = 360.0f / cook_torrance_descs.size();
  float hue = 0.0f;
  for (auto& desc : cook_torrance_descs) {
    desc.albedo = HLSAtoRGBA(hue, 0.5f, 1.0f, 1.0f);
    desc.shading_model = PBRMaterialDescriptor::ShadingModel::kConstant;
    cook_torrance_materials.updateMaterialProperties(desc);
    hue += hue_step;
  }
  cook_torrance_materials.updateBufferData(*material_ssbo);
  draw_spheres();
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "pbr_constant_shading_test"));

  // Modify point light and update light ssbo
  point_light_desc->color = glm::vec3{0.1f, 0.4f, 0.8f};
  point_light_desc->multiplier = 1.0f;
  point_light_desc->do_decay = false;
  lightmgr.updateLightProperties(*point_light_desc);
  lightmgr.updateBufferData(*light_data_ssbo);

  // Draw Blinn-Phong grid
  blinn_phong_materials.updateBufferData(*material_ssbo);
  draw_spheres();
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "pbr_blinn_phong_test"));

  // Cleanup resources
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
  resource_mgr.destroyPipeline(std::move(pipeline));
  resource_mgr.destroyBuffer(std::move(instances_ssbo));
  resource_mgr.destroyBuffer(std::move(material_ssbo));
  resource_mgr.destroyBuffer(std::move(model_matrices_ubo));
  resource_mgr.destroyBuffer(std::move(projection_ubo));
  resource_mgr.destroyBuffer(std::move(light_data_ssbo));
  mesh_data.destroyResources(resource_mgr);
}

//
// PBRScene test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, PBRSceneTest) {
#else
TEST_F(RenderTest, PBRSceneTest) {
#endif
  const uint32_t kRenderWidth = 300;
  const uint32_t kRenderHeight = 300;
  auto& device = *this->device_contexts_[0];
  auto& resource_mgr = device.getResourceManager();
  auto& shader_mgr = resource_mgr.getShaderManager();

  //
  // Init instances and material properties
  //

  const int kNumRows = 6;
  const int kNumColumns = 6;
  const int kNumInstances = kNumRows * kNumColumns;
  const float kInstanceScale = 0.15f;
  std::vector<glm::vec4> instances_host_buffer(kNumInstances);

  PBRScene scene(resource_mgr);

  // Create grid of spheres alternating cook-torrance and blinn-phong
  const glm::vec4 cook_torrance_albedo{0.5f, 0.8f, 0.4f, 1.0f};
  const glm::vec4 blinn_phong_albedo{0.1f, 0.6f, 0.1f, 1.0f};
  const float x_step = 2.f / (kNumColumns - 1);
  const float y_step = 2.f / (kNumRows - 1);
  const float roughness_step = 1.f / (kNumColumns - 1);
  const float metallic_step = 1.f / (kNumRows - 1);
  const float glossiness_step = 40.f / (kNumColumns - 1);
  const float spec_strength_step = 1.5f / (kNumRows - 1);
  int vi = 0;
  float roughness = 0.0f;
  float glossiness = 1.0f;
  for (float y = 1.0f; y >= -1.0f;
       y -= y_step, roughness += roughness_step, glossiness += glossiness_step) {
    float metallic = 0.0f;
    float spec_strength = 0.0f;
    for (float x = -1.0f; x <= 1.0f;
         x += x_step, metallic += metallic_step, spec_strength += spec_strength_step) {
      instances_host_buffer[vi] = glm::vec4{x, y, 0.0f, kInstanceScale};
      scene.addCookTorranceMaterial(PBRMaterialDescriptor::ColorSource::kConstant,
                                    cook_torrance_albedo,
                                    1.0f,
                                    roughness,
                                    metallic);
      scene.addBlinnPhongMaterial(PBRMaterialDescriptor::ColorSource::kConstant,
                                  blinn_phong_albedo,
                                  1.0f,
                                  glossiness,
                                  spec_strength);
      vi++;
    }
  }

  uint64_t buffer_size = instances_host_buffer.size() * sizeof(glm::vec4);

  auto instances_ssbo = resource_mgr.createBuffer(
      "Instances",
      {BufferType::kUnspecified, buffer_size, BufferUsageBits::kStorageBufferBit});

  instances_ssbo->updateSubData(instances_host_buffer.data(), buffer_size, 0);

  // Model matrices
  struct ModelMatrices {
    glm::mat4 model_tm{1};
    glm::mat4 normal_tm{1};
  };

  ModelMatrices model_matrices;
  auto model_matrices_ubo =
      resource_mgr.createBuffer("Model Matrices UBO",
                                {gfx::BufferType::kUnspecified,
                                 sizeof(ModelMatrices),
                                 gfx::BufferUsageBits::kUniformBufferBit,
                                 gfx::BufferAccessType::kHostVisible});
  model_matrices_ubo->updateSubData(&model_matrices, sizeof(ModelMatrices), 0);

  // Camera
  auto camera =
      std::make_unique<Camera>(Camera::Projection::kOrthographic, Camera::Type::kLookAt);
  camera->setClip(10.f, 0.f);
  camera->setPosition(glm::vec3{0.0f, 0.0f, 2.5f});
  camera->setOrthoParams(
      -glm::vec2{1.4f - kInstanceScale}, glm::vec2{1.4f - kInstanceScale}, 10.f, 0.f);

  auto projection_ubo = Camera::createBuffer(resource_mgr);
  camera->updateBufferData(*projection_ubo);

  scene.addParallelLight(
      glm::normalize(glm::vec3{0.5, -0.25, 0.5}), glm::vec3{1.5, 1.25, 1.0}, 0.8);
  scene.addPointLight(glm::vec3{-15, -35, 0}, glm::vec3{0.2, 0.2, 0.9}, 0.8, false);
  // Save the LightDesc to test updating a light
  auto& point_light_desc =
      scene.addPointLight(glm::vec3{-5, 35, -5}, glm::vec3{0.8, 0.2, 0.0}, 1500.0, true);

  scene.updateMaterialDataBuffer();
  scene.updateLightDataBuffer();

  //
  // Materials
  //
  auto builders = shader_mgr.createBuilderVector(
      {{"Shading/shadingBase.vert"}, {"Shading/shadingMain.frag"}});
  builders[0]->appendTemplate("Shading/shadingMain.vert");
  builders[0]->setExternalUniformBuffers(
      {"MODEL_MATRICES_UBO_TYPE", "PROJECTION_UBO_TYPE"});

  auto caches = shader_mgr.createCacheVector(std::move(builders), true);
  auto material = resource_mgr.createMaterial("Material", caches);

  material->bindShaderStorageBufferToBlock("INSTANCE_DATA_SSBO", *instances_ssbo);
  material->bindExternalUniformBufferToBlock("PROJECTION_UBO_TYPE", *projection_ubo);
  material->bindExternalUniformBufferToBlock("MODEL_MATRICES_UBO_TYPE",
                                             *model_matrices_ubo);

  scene.bindBuffersToMaterial(*material);
  material->updateDescriptorSets();

  // RenderPass and Framebuffer
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        kRenderWidth,
                        kRenderHeight,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

  auto render_pass = resource_mgr.createRenderPass("RenderPass",
                                                   attachment_mgr.getLayout(),
                                                   gfx::RenderPass::ClearBits::kAll,
                                                   ImageLayout::kUndefined,
                                                   ImageLayout::kAttachment);

  auto framebuffer = resource_mgr.createFramebuffer(
      "Framebuffer", *render_pass, attachment_mgr, kRenderWidth, kRenderHeight, 1);

  // Mesh
  std::vector<std::string> material_attrs = {{"in_position"}, {"in_normal"}};
  auto mesh_data = build_mesh_draw_data(
      resource_mgr, *build_uv_sphere(40, 20, true), "Sphere", material_attrs, *material);

  // Pipeline
  PipelineDescriptor pipeline_desc;
  pipeline_desc.setFaceCullMode(FaceCullMode::kBack);
  auto pipeline = resource_mgr.createGraphicsPipeline(
      "Shaded", *material, pipeline_desc, mesh_data.pa.get());
  pipeline->create(*render_pass);

  // Set viewport
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, kRenderWidth, kRenderHeight);

  // Draw lambda
  auto draw_spheres = [&]() {
    device.getCommandList()
        .beginRenderPass(*render_pass, *framebuffer)
        .drawIndexed(*pipeline,
                     *mesh_data.vbo,
                     *mesh_data.ibo,
                     mesh_data.num_indices,
                     0,
                     0,
                     kNumInstances)
        .endRenderPass()
        .flush("Test");
  };

  // Draw sphere grid
  draw_spheres();
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "pbr_scene_test_0"));

  // Modify albedo
  float hue_step = 360.0f / kNumInstances;
  float hue = 0.0f;
  scene.iterateMaterialDescs([&](PBRMaterialDescriptor& desc) {
    desc.albedo = HLSAtoRGBA(hue, 0.5f, 1.0f, 1.0f);
    scene.updateMaterialProperties(desc);
    hue += hue_step;
  });
  scene.updateMaterialDataBuffer();

  // Modify point light and update light ssbo
  point_light_desc.color = glm::vec3{0.1f, 0.4f, 0.8f};
  point_light_desc.multiplier = 1.0f;
  point_light_desc.do_decay = false;
  scene.updateLightProperties(point_light_desc);
  scene.updateLightDataBuffer();

  draw_spheres();
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "pbr_scene_test_1"));

  // Cleanup resources
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
  resource_mgr.destroyPipeline(std::move(pipeline));
  resource_mgr.destroyBuffer(std::move(instances_ssbo));
  resource_mgr.destroyBuffer(std::move(model_matrices_ubo));
  resource_mgr.destroyBuffer(std::move(projection_ubo));
  scene.destroyResources();
  mesh_data.destroyResources(resource_mgr);
}

//
// Compute Test
//
TEST_F(VulkanRenderTest, DISABLED_ComputeTest) {
  auto& device = *this->device_contexts_[0];

  // shader
  auto caches = this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
      {{"RenderTests/computeTest.comp"}});
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("Test", caches);
  ASSERT_NE(material, nullptr);

  // pipeline
  auto pipeline = resource_mgr.createComputePipeline("Test", *material);
  pipeline->create();

  // Deliberately call pipeline->create twice to ensure recreating works properly
  pipeline->create();

  constexpr uint32_t kWidth = 3200;
  constexpr uint32_t kHeight = 2400;
  constexpr uint32_t kNumPixels = kWidth * kHeight;
  constexpr uint64_t kBufferSize = kNumPixels * 4 * sizeof(float);
  uint32_t subgroup_size = device.getLimits().subgroup_size;
  ASSERT_GT(subgroup_size, 0u);

  // create a directly-host-visible SSBO
  auto ssbo = resource_mgr.createHostVisibleBuffer(
      "Test",
      {BufferType::kUnspecified, kBufferSize, BufferUsageBits::kStorageBufferBit});
  ASSERT_NE(ssbo, nullptr);
  auto const& ssbo_buffer = ssbo->getSourceBufferWrapper();

  // bind it to the material
  material->bindShaderStorageBufferToBlock("buf", ssbo_buffer);

  // prepare material for work
  material->updateDescriptorSets();

  // run
  device.getCommandList()
      .dispatchCompute(*pipeline, 0u, kWidth / subgroup_size, kHeight / subgroup_size, 1u)
      .flush(kTestFlushName);

  // read back (converting from raw float[4] to RGBA8)
  float* float_image{nullptr};
  ssbo->map((void**)&float_image);
  EXPECT_NE(nullptr, float_image);
  std::vector<uint8_t> byte_image(kNumPixels * 4);
  for (uint32_t i = 0; i < kNumPixels * 4; i++) {
    byte_image[i] = *float_image++ * 255;
  }
  ssbo->unmap();

  // Image operation (golden-image compare)
  EXPECT_TRUE(
      this->golden_image_->compare(byte_image, kWidth, kHeight, 4, "compute_test"));

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  resource_mgr.destroyHostVisibleBuffer(std::move(ssbo));
  material = nullptr;
}

//
// Buffer Device Address Test
//
TEST_F(VulkanRenderTest, BufferDeviceAddressTest) {
  auto& device = *this->device_contexts_[0];

  // shader
  auto caches = this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
      {{"RenderTests/bdaTest.comp"}});
  ASSERT_NE(caches.size(), size_t{0});
  ASSERT_NE(caches[0]->getSpirv().size(), size_t{0});

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("Test", caches);
  ASSERT_NE(material, nullptr);

  struct PushConstants {
    uint64_t qob;
    uint64_t chunk;
    uint64_t results;
  };

  // pipeline
  PushConstantRange pcr(ShaderStageBits::kCompute, 0, sizeof(PushConstants));
  auto pipeline = resource_mgr.createComputePipeline("Test", *material, {}, {pcr});
  pipeline->create();

  constexpr uint32_t kNumRows = 100;

  uint32_t subgroup_size = device.getLimits().subgroup_size;
  ASSERT_GT(subgroup_size, 0u);

  // create some more directly-host-visible SSBOs for BDA experiments
  // QOB
  static constexpr BufferUsageBits usage_bits =
      BufferUsageBits::kStorageBufferBit | BufferUsageBits::kDeviceAddressBit;
  auto qob = resource_mgr.createHostVisibleBuffer(
      "QOB", {BufferType::kUnspecified, sizeof(uint64_t) * kNumRows, usage_bits});
  ASSERT_NE(qob, nullptr);
  auto const& qob_buffer = qob->getSourceBufferWrapper();
  // chunks
  auto chunk = resource_mgr.createHostVisibleBuffer(
      "Chunk", {BufferType::kUnspecified, sizeof(double) * kNumRows * 2, usage_bits});
  ASSERT_NE(chunk, nullptr);
  auto const& chunk_buffer = chunk->getSourceBufferWrapper();
  // results
  auto results = resource_mgr.createHostVisibleBuffer(
      "Results", {BufferType::kUnspecified, sizeof(double) * kNumRows * 2, usage_bits});
  ASSERT_NE(results, nullptr);
  auto const& results_buffer = results->getSourceBufferWrapper();

  // prepare material for work
  material->updateDescriptorSets();

  // push constant values
  PushConstants push_constants;
  push_constants.qob = qob_buffer.getBuffer().getDeviceAddress();
  push_constants.chunk = chunk_buffer.getBuffer().getDeviceAddress();
  push_constants.results = results_buffer.getBuffer().getDeviceAddress();

  // build the chunk
  {
    double* chunk_ptr{nullptr};
    chunk->map((void**)&chunk_ptr);
    EXPECT_NE(nullptr, chunk_ptr);
    for (uint32_t i = 0; i < kNumRows; i++) {
      uint32_t chunk_idx = i * 2;
      // x and y for this row
      chunk_ptr[chunk_idx] = double(i);
      chunk_ptr[chunk_idx + 1] = -double(i);
    }
    chunk->unmap();
  }

  // build the QOB
  {
    uint64_t* qob_ptr{nullptr};
    qob->map((void**)&qob_ptr);
    EXPECT_NE(nullptr, qob_ptr);
    for (uint32_t i = 0; i < kNumRows; i++) {
      // the actual device address for each x/y pair
      qob_ptr[i] = push_constants.chunk + (i * 2 * sizeof(double));
    }
    qob->unmap();
  }

  // clear the results
  {
    double* results_ptr{nullptr};
    results->map((void**)&results_ptr);
    EXPECT_NE(nullptr, results_ptr);
    memset(results_ptr, 0, sizeof(double) * kNumRows * 2);
    results->unmap();
  }

  // run
  const uint32_t group_count_x = (kNumRows + subgroup_size - 1) / subgroup_size;
  device.getCommandList()
      .setPushConstants(*pipeline,
                        "Push Constants",
                        ShaderStageBits::kCompute,
                        &push_constants,
                        sizeof(PushConstants))
      .dispatchCompute(*pipeline, 0u, group_count_x, 1u, 1u)
      .flush(kTestFlushName);

  // validate the results
  bool results_correct{true};
  {
    double* results_ptr{nullptr};
    results->map((void**)&results_ptr);
    EXPECT_NE(nullptr, results_ptr);
    for (uint32_t i = 0; i < kNumRows; i++) {
      double expected_x = double(i);
      double expected_y = -double(i);
      uint32_t results_idx = i * 2;
      double x = results_ptr[results_idx];
      double y = results_ptr[results_idx + 1];
      if (x != expected_x || y != expected_y) {
        results_correct = false;
        break;
      }
    }
    results->unmap();
  }
  EXPECT_EQ(results_correct, true);

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  resource_mgr.destroyHostVisibleBuffer(std::move(qob));
  resource_mgr.destroyHostVisibleBuffer(std::move(chunk));
  resource_mgr.destroyHostVisibleBuffer(std::move(results));
  material = nullptr;
}

//
// Init Render Buffer Test
//
#define TIME_INIT_RENDER_BUFFER 0
#define TEST_INIT_RENDER_BUFFER 0
#if USE_TYPED_TEST
TYPED_TEST(TypedRenderTest, InitRenderBufferTest) {
#else
TEST_F(RenderTest, InitRenderBufferTest) {
#endif
  auto& device = *this->device_contexts_[0];

  // shader
  auto caches = this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
      {{"RenderTests/initRenderBufferTest.comp"}});
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("Test", caches);
  ASSERT_NE(material, nullptr);

  // pipeline
  auto pipeline = resource_mgr.createComputePipeline("Test", *material);
  pipeline->create();

  // 2GB render buffer
  constexpr uint64_t kNumBytes = 2000000000ul;

  // workgroup math
  constexpr uint32_t kWorkgroupSize = 32u;
  constexpr uint32_t kNumValues = kNumBytes / sizeof(int64_t);
  constexpr uint32_t kNumValuesRoundedUp =
      (kNumValues + (kWorkgroupSize - 1)) & ~(kWorkgroupSize - 1);
  constexpr uint32_t kTotalWorkgroups = kNumValuesRoundedUp / kWorkgroupSize;

  constexpr uint32_t kNumWorkgroupsX = 65535u;  // min required by vulkan
  constexpr uint32_t kNumWorkgroupsY =
      (kTotalWorkgroups + kNumWorkgroupsX - 1) / kNumWorkgroupsX;  // round up

#if TEST_INIT_RENDER_BUFFER
  // create a host-visible shader storage buffer
  auto buffer_wrapper = resource_mgr.createHostVisibleBuffer(
      "Test", {BufferType::kShaderStorageBuffer, kNumBytes});
  ASSERT_NE(buffer_wrapper, nullptr);
  auto const& query_output_buffer = buffer_wrapper->getSourceBufferWrapper();

  // bind it to the material
  material->bindShaderStorageBufferToBlock("query_output_buffer", &query_output_buffer);
#else
  // create a device-only vertex buffer (tagged to allow binding as SSBO)
  auto buffer_wrapper = resource_mgr.createBuffer(
      "Test", {BufferType::kVertexBuffer, kNumBytes, BufferUsageBits::kStorageBufferBit});
  ASSERT_NE(buffer_wrapper, nullptr);
  auto const* query_output_buffer =
      static_cast<const VertexBuffer*>(buffer_wrapper.get());

  // bind it to the material
  material->bindShaderStorageBufferToBlock("query_output_buffer", *query_output_buffer);
#endif

  // set other material uniforms and finalize
  material->setUniformAttribute("num_values", kNumValues);
  material->updateDescriptorSets();

#if TIME_INIT_RENDER_BUFFER
  // prepare to time
  device.getCommandExecutor().waitForCompletion(true);
  auto timer = timer_start();
#endif

  // run
  device.getCommandList()
      .dispatchCompute(*pipeline, 0u, kNumWorkgroupsX, kNumWorkgroupsY, 1u)
      .flush(kTestFlushName, gfx::CommandList::SubmitType::kWaitComplete);

#if TIME_INIT_RENDER_BUFFER
  // time
  auto const wall_time =
      timer_stop<std::chrono::steady_clock::time_point, std::chrono::microseconds>(timer);
  std::cout << "Init Render Buffer took " << float(wall_time) / 1000.0f << "ms"
            << std::endl;
#endif

#if TEST_INIT_RENDER_BUFFER
  // read back and check values
#if TIME_INIT_RENDER_BUFFER
  auto timer2 = timer_start();
#endif
  int64_t* values{nullptr};
  buffer_wrapper->map((void**)&values);
  EXPECT_NE(nullptr, values);
  for (uint32_t i = 0; i < kNumValuesRoundedUp; i++) {
    CHECK_EQ(values[i], i) << "Failed at " << i;
  }
  buffer_wrapper->unmap();
#if TIME_INIT_RENDER_BUFFER
  auto const wall_time2 = timer_stop(timer2);
  std::cout << "Validate values took " << wall_time2 << "ms" << std::endl;
#endif
#endif

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
#if TEST_INIT_RENDER_BUFFER
  resource_mgr.destroyHostVisibleBuffer(std::move(buffer_wrapper));
#else
  resource_mgr.destroyBuffer(std::move(buffer_wrapper));
#endif
  material = nullptr;
}

// DeviceLostTest
// Uses a fragment shader with a non-terminating loop to test
// detection and recovery from DEVICE_LOST error
// This test is intentionally disabled due to its unpredictable impact on execution time
// and other GPU usage. The test can take anywhere from a few seconds to a minute before
// the driver finally gives up, and it will freeze a desktop while stuck
TEST_F(VulkanRenderTest, DISABLED_DeviceLostTest) {
  // begin_renderdoc_vulkan_capture();
  constexpr std::array<float, 2> dimensions{static_cast<float>(render_width),
                                            static_cast<float>(render_height)};
  PipelineDescriptor pipeline_desc;
  {
    auto& device = *this->device_contexts_[0];

    // Generate spirv
    auto timeout_caches =
        this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
            {{"DriverTests/fullScreenTriangle.vert"},
             {"RenderTests/deviceLostTest.frag"}});
    ASSERT_TRUE(validate_shader_caches(timeout_caches));

    auto& resource_mgr = device.getResourceManager();

    // materials
    auto timeout_material = resource_mgr.createMaterial("Test", timeout_caches);
    ASSERT_NE(timeout_material, nullptr);
    timeout_material->setUniformAttribute("imageSize", dimensions);
    timeout_material->setUniformAttribute("invertY", 0);
    timeout_material->setUniformAttribute("loopEnd", 0);
    timeout_material->updateDescriptorSets();

    // attachment manager and textures
    auto [attachment_mgr, textures] =
        build_attachments(resource_mgr,
                          render_width,
                          render_height,
                          {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

    // renderpass and framebuffer
    auto render_pass = resource_mgr.createRenderPass("Test",
                                                     attachment_mgr.getLayout(),
                                                     RenderPass::ClearBits::kAll,
                                                     ImageLayout::kUndefined);
    ASSERT_NE(render_pass, nullptr);
    auto framebuffer = resource_mgr.createFramebuffer(
        "Test", *render_pass, attachment_mgr, render_width, render_height, 1u);
    ASSERT_NE(framebuffer, nullptr);

    // pipelines
    auto timeout_pipeline =
        resource_mgr.createGraphicsPipeline("Test", *timeout_material, pipeline_desc);
    timeout_pipeline->create(*render_pass);

    // render via command list
    device.getCommandExecutor().setDefaultViewportAndRenderArea(
        0, 0, render_width, render_height);
    auto& cmd_list = device.getCommandList();
    cmd_list.beginRenderPass(*render_pass, *framebuffer)
        .drawFullscreen(*timeout_pipeline)
        .endRenderPass();

    // suppress validation messages which will result from the forced teardown
    VulkanPlatform::pushSuppressValidationMessages();
    EXPECT_THROW(cmd_list.flush(kTestFlushName), gfx::DeviceLostError);

    // Destroy resources
    // These would normally result in validation errors since the VkDevice is
    // no longer valid, but we need to cleanup our internals
    resource_mgr.destroyPipeline(std::move(timeout_pipeline));
    timeout_material = nullptr;
    resource_mgr.destroyFramebuffer(std::move(framebuffer));
    for (auto& texture : textures) {
      resource_mgr.destroyTexture(std::move(texture));
    }
    resource_mgr.destroyRenderPass(std::move(render_pass));
  }

  // destroy and recreate DeviceContexts
  this->recreateDeviceContexts();
  // restore validation messages
  VulkanPlatform::popSuppressValidationMessages();

  //////////////////////////////////////////
  // Verify that we reinitialized and can render successfully
  {
    auto& device = *this->device_contexts_[0];

    auto render_caches =
        this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
            {{"DriverTests/fullScreenTriangle.vert"},
             {"RenderTests/drawFullScreenTest.frag"}});
    ASSERT_TRUE(validate_shader_caches(render_caches));

    auto& resource_mgr = device.getResourceManager();

    // draw fullscreen material
    auto render_material = resource_mgr.createMaterial("Test", render_caches);
    ASSERT_NE(render_material, nullptr);
    render_material->setUniformAttribute("imageSize", dimensions);
    render_material->setUniformAttribute("invertY", 0);

    render_material->updateDescriptorSets();

    // attachment manager and textures
    auto [attachment_mgr, textures] =
        build_attachments(resource_mgr,
                          render_width,
                          render_height,
                          {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

    // renderpass and framebuffer
    auto render_pass = resource_mgr.createRenderPass("Test",
                                                     attachment_mgr.getLayout(),
                                                     RenderPass::ClearBits::kAll,
                                                     ImageLayout::kUndefined);
    ASSERT_NE(render_pass, nullptr);
    auto framebuffer = resource_mgr.createFramebuffer(
        "Test", *render_pass, attachment_mgr, render_width, render_height, 1u);
    ASSERT_NE(framebuffer, nullptr);

    auto render_pipeline =
        resource_mgr.createGraphicsPipeline("Test", *render_material, pipeline_desc);
    render_pipeline->create(*render_pass);

    device.getCommandExecutor().setDefaultViewportAndRenderArea(
        0, 0, render_width, render_height);
    auto& cmd_list = device.getCommandList();
    cmd_list.beginRenderPass(*render_pass, *framebuffer)
        .drawFullscreen(*render_pipeline)
        .endRenderPass()
        .flush(kTestFlushName);

    // Image operation (golden-image compare)
    EXPECT_TRUE(this->golden_image_->compare(
        *framebuffer, Framebuffer::Attachment::kColor0, "device_lost_test"));

    // destroy resources
    resource_mgr.destroyPipeline(std::move(render_pipeline));
    render_material = nullptr;
    resource_mgr.destroyFramebuffer(std::move(framebuffer));
    for (auto& texture : textures) {
      resource_mgr.destroyTexture(std::move(texture));
    }
    resource_mgr.destroyRenderPass(std::move(render_pass));
  }
}

}  // namespace GfxDriverTests
