# Cuda stack
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb && \
    dpkg -i cuda-keyring_1.0-1_all.deb && \
    apt-get update && \
    apt-get install -y cuda libarrow-cuda-dev

ENV PATH=/usr/local/cuda-11.7/bin${PATH:+:${PATH}}

