/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include "GfxDriver/Resources/BufferWrapper.h"
#include "GfxDriver/Resources/ResourceManager.h"

namespace QueryRenderer {

//
// This class encapsulates the mechanism and resources that allow a GLSL
// shader to translate device memory addresses from the CUDA (or some other
// address space to the Vulkan address space, for the purpose of accessing
// data generated by CUDA using the Buffer Device Address shading extension.
//
// QueryBufferManager maintains a vector of Vulkan buffers which are created
// as virtual wrappers for CUDA slab allocations. The base address and size
// of the CUDA allocation, along with an exported handle (a POSIX File
// Descriptor, on Linux) are provided for each known slab allocation on the
// GPU in question.
//
// Note that the wrapper buffers do not actually need to be explicitly bound
// in the shaders. It is only necessary that the correct base address of one
// of the buffers be provided (in Vulkan address space) to the Buffer Device
// Address access binding.
//
// This class manages the address table as well as a shareable Uniform Buffer
// which contains a table to allow the shaders to perform a run-time mapping
// from a CUDA address to a Vulkan address. This Uniform Buffer must be bound
// to any shader that needs it, and there is shared GLSL utility code that
// implements the mapping and read functions, for example to read a data item
// (double, uint32_t etc.) from a given CUDA address found in the query output.
//

class SlabAddressTable {
 public:
  explicit SlabAddressTable(gfx::ResourceManager& resource_mgr);
  SlabAddressTable() = delete;
  ~SlabAddressTable();

  // for binding to the materials
  const gfx::BufferWrapper& getTableBuffer() const;

  // for building/rebuilding the table
  void reset();
  void addEntry(const uint64_t cuda_addr, const uint64_t vulkan_addr);
  void finalizeAndUpdateBuffer();

  // for reading the table
  // should probably just remove this class and do all this directly in QBM
  const size_t numEntries() const;
  const std::pair<uint64_t, uint64_t> getEntry(const size_t index) const;

  // for shutdown
  void destroyResources();

 private:
  gfx::ResourceManager& resource_mgr_;

  struct Entry {
    uint64_t cuda;
    uint64_t vulkan;
  };
  std::vector<Entry> table_;

  // Currently we only support 64 slabs per device.
  // This may need to increase, or be made dynamic.
  // Note that a dynamic table will require shaders
  // to be rebuilt if the length changes.
  static constexpr size_t kMaxSlabs = 64;
  static constexpr size_t kTableBufferSize = (kMaxSlabs + 1) * sizeof(Entry);

  gfx::BufferWrapperUqPtr table_buffer_;
};

}  // namespace QueryRenderer
