#!/bin/bash

cd build
mkdir -p Tests/tmp
bin/initdb -f Tests/tmp
cd -

result="success"
for test in PlanTest ExecuteTest StorageTest ResultSetTest ResultSetBaselineRadixSortTest ImportTest
do
	cd build/Tests && eval ./$test --gtest_output=xml:../
	if [ $? != 0 ]
	then
		result="fail"
	fi
	cd -
done
if [ $result == "fail" ]
then
	echo "--------- Sanity Tests Failed ---------."
	exit 1
else
	echo "+++++++++ Sanity Tests Passed +++++++++."
fi
