#!/bin/bash

result="success"
for test in Tests/PlanTest Tests/ExecuteTest
do
	cd build && eval $test
	if [ $? != 0 ]
	then
		result="fail"
	fi
	cd -
done
if [ $result == "fail" ]
then
	echo "--------- Sanity Tests Failed ---------."
	exit 1
else
	echo "+++++++++ Sanity Tests Passed +++++++++."
fi
