#!/bin/bash

if [ ! -d data ]; then
    mkdir data
    ./bin/initdb -f --path data
    echo "Download and insert sample data? Y/n"
    read choice
    if [ -z "$choice" ]; then choice="Y"; fi
    case $choice in
        [yY]* )
            DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
            . $DIR/insert_sample_data ;;
    esac
fi

if ! pgrep mapd_server; then
    ./bin/mapd_server data --cpu &
fi

if ! pgrep mapd_http_server; then
    ./bin/mapd_http_server &
fi

if [ -d frontend ]; then
    pushd frontend
    if [ ! -e downloads ]; then
        ln -s ../data/mapd_export downloads
    fi
    popd

    pushd upload_server
    if [ ! -e uploads ]; then
        #ln -s ../data/mapd_import uploads
        mkdir -p uploads
    fi
    trap 'kill -TERM $WEBPID' TERM INT
    PORT=9092 nodejs/bin/node index.js &
    WEBPID=$!

    MAPDFRONTEND="http://localhost:9092"
    if [ ! -z "$MAPDDASH" ]; then
        MAPDFRONTEND="$MAPDFRONTEND/?style=light-style&platform=mapd&host=localhost&port=9090&db=mapd&$MAPDDASH"
    fi
    if hash open 2>/dev/null; then
        open $MAPDFRONTEND
    elif hash xdg-open 2>/dev/null; then
        xdg-open $MAPDFRONTEND
    else
        echo "Navigate to: $MAPDFRONTEND"
    fi
    wait $WEBPID
    trap - TERM INT
    wait $WEBPID
fi
