/*
 * SPDX-FileCopyrightText: Copyright (c) 2020-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#define WIDTH 3200
#define HEIGHT 2400
#define WORKGROUP_SIZE 32

layout (local_size_x = WORKGROUP_SIZE, local_size_y = WORKGROUP_SIZE, local_size_z = 1) in;

layout(std430, binding = 0) buffer buf
{
  vec4 imageData[];
};

void main() {
  // In order to fit the work into workgroups, some unnecessary threads are launched.
  // We terminate those threads here.
  if (gl_GlobalInvocationID.x >= WIDTH || gl_GlobalInvocationID.y >= HEIGHT) {
    return;
  }

  float x = float(gl_GlobalInvocationID.x) / float(WIDTH);
  float y = float(gl_GlobalInvocationID.y) / float(HEIGHT);

  // What follows is code for rendering the mandelbrot set.
  vec2 uv = vec2(x, y);
  float n = 0.0;
  vec2 c = vec2(-0.445, 0.0) + (uv - 0.5) * (2.0 + 1.7 * 0.2);
  vec2 z = vec2(0.0);
  const int M = 128;
  for (int i = 0; i < M; i++) {
    z = vec2(z.x * z.x - z.y * z.y, 2.0 * z.x * z.y) + c;
    if (dot(z, z) > 2.0) {
      break;
    }
    n++;
  }

  // We use a simple cosine palette to determine color:
  // http://iquilezles.org/www/articles/palettes/palettes.htm
  float t = float(n) / float(M);
  vec3 d = vec3(0.3, 0.3, 0.5);
  vec3 e = vec3(-0.2, -0.3, -0.5);
  vec3 f = vec3(2.1, 2.0, 3.0);
  vec3 g = vec3(0.0, 0.1, 0.0);
  vec4 color = vec4(d + e * cos(6.28318 * (f * t + g)), 1.0);

  // Store the rendered mandelbrot set into a storage buffer:
  imageData[WIDTH * gl_GlobalInvocationID.y + gl_GlobalInvocationID.x] = color;
}
