#ifndef THRIFTSERVICE_H
#define THRIFTSERVICE_H

enum ThriftService {
  kCONNECT,
  kDISCONNECT,
  kSWITCH_DATABASE,
  kREPORT_DATABASE,
  kSQL,
  kGET_TABLES,
  kGET_PHYSICAL_TABLES,
  kGET_VIEWS,
  kGET_DATABASES,
  kGET_USERS,
  kSET_EXECUTION_MODE,
  kGET_VERSION,
  kGET_MEMORY_GPU,
  kGET_MEMORY_CPU,
  kGET_MEMORY_SUMMARY,
  kGET_TABLE_DETAILS,
  kCLEAR_MEMORY_GPU,
  kCLEAR_MEMORY_CPU,
  kINTERRUPT,
  kSET_TABLE_EPOCH,
  kSET_TABLE_EPOCH_BY_NAME,
  kGET_TABLE_EPOCH,
  kGET_TABLE_EPOCH_BY_NAME,
  kGET_SERVER_STATUS,
  kIMPORT_DASHBOARD,
  kGET_ROLES,
  kGET_OBJECTS_FOR_GRANTEE,
  kGET_OBJECT_PRIVS,
  kGET_ROLES_FOR_USER,
  kGET_HARDWARE_INFO,
  kSET_LICENSE_KEY,
  kGET_LICENSE_CLAIMS,
  kGET_COMPLETION_HINTS,
  kGET_DASHBOARDS,
  kGET_DASHBOARD
};

#endif
