/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

extern "C" RUNTIME_EXPORT bool Geos_Wkb_Wkb(int op,
                                            int arg1_type,
                                            int8_t* arg1_coords,
                                            int64_t arg1_coords_size,
                                            int32_t* arg1_meta1,
                                            int64_t arg1_meta1_size,
                                            int32_t* arg1_meta2,
                                            int64_t arg1_meta2_size,
                                            int32_t arg1_ic,
                                            int32_t arg1_srid_in,
                                            int32_t arg1_srid_out,
                                            int arg2_type,
                                            int8_t* arg2_coords,
                                            int64_t arg2_coords_size,
                                            int32_t* arg2_meta1,
                                            int64_t arg2_meta1_size,
                                            int32_t* arg2_meta2,
                                            int64_t arg2_meta2_size,
                                            int32_t arg2_ic,
                                            int32_t arg2_srid_in,
                                            int32_t arg2_srid_out,
                                            int* result_type,
                                            int8_t** result_coords,
                                            int64_t* result_coords_size,
                                            int32_t** result_meta1,
                                            int64_t* result_meta1_size,
                                            int32_t** result_meta2,
                                            int64_t* result_meta2_size,
                                            int32_t result_srid_out);

extern "C" RUNTIME_EXPORT bool Geos_Wkb_Wkb_Predicate(int op,
                                                      int arg1_type,
                                                      int8_t* arg1_coords,
                                                      int64_t arg1_coords_size,
                                                      int32_t* arg1_meta1,
                                                      int64_t arg1_meta1_size,
                                                      int32_t* arg1_meta2,
                                                      int64_t arg1_meta2_size,
                                                      int32_t arg1_ic,
                                                      int32_t arg1_srid_in,
                                                      int32_t arg1_srid_out,
                                                      int arg2_type,
                                                      int8_t* arg2_coords,
                                                      int64_t arg2_coords_size,
                                                      int32_t* arg2_meta1,
                                                      int64_t arg2_meta1_size,
                                                      int32_t* arg2_meta2,
                                                      int64_t arg2_meta2_size,
                                                      int32_t arg2_ic,
                                                      int32_t arg2_srid_in,
                                                      int32_t arg2_srid_out,
                                                      bool* result);

extern "C" RUNTIME_EXPORT bool Geos_Wkb_double(int op,
                                               int arg1_type,
                                               int8_t* arg1_coords,
                                               int64_t arg1_coords_size,
                                               int32_t* arg1_meta1,
                                               int64_t arg1_meta1_size,
                                               int32_t* arg1_meta2,
                                               int64_t arg1_meta2_size,
                                               int32_t arg1_ic,
                                               int32_t arg1_srid_in,
                                               int32_t arg1_srid_out,
                                               double arg2,
                                               int* result_type,
                                               int8_t** result_coords,
                                               int64_t* result_coords_size,
                                               int32_t** result_meta1,
                                               int64_t* result_meta1_size,
                                               int32_t** result_meta2,
                                               int64_t* result_meta2_size,
                                               int32_t result_srid_out);

extern "C" RUNTIME_EXPORT bool Geos_Wkb(int op,
                                        int arg_type,
                                        int8_t* arg_coords,
                                        int64_t arg_coords_size,
                                        int32_t* arg_meta1,
                                        int64_t arg_meta1_size,
                                        int32_t* arg_meta2,
                                        int64_t arg_meta2_size,
                                        int32_t arg_ic,
                                        int32_t arg_srid_in,
                                        int32_t arg_srid_out,
                                        bool* result);
