# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: heavydb build and pack

runs:
  using: composite
  steps:
    - name: placeholder
      shell: bash
      run: "true"
