/*
 * SPDX-FileCopyrightText: Copyright (c) 2021-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#define USE_SUBGROUPS <useSubgroups>

#if USE_SUBGROUPS == 1
#extension GL_KHR_shader_subgroup_vote: enable
#extension GL_KHR_shader_subgroup_arithmetic: enable
#extension GL_EXT_shader_subgroup_extended_types_int64: enable
#endif

layout (local_size_x = <workgroupSize>, local_size_y = 1, local_size_z = 1) in;

layout(r32ui) uniform restrict readonly uimage2DArray inTxArrayPixelCounter;

layout(std430) buffer EXTENTS_SSBO {
  uint64_t totalNonZeroCount;
  uint64_t totalSqrDiff;
  uint32_t minCount;
  uint32_t maxCount;
  uint32_t numNonZeroCount;
} extents;

layout(std430) uniform FRAGMENT_STATS_UBO_TYPE {
  uint32_t imageWidth;
};

void main() {
  if (gl_GlobalInvocationID.x >= imageWidth) {
    return;
  }

  uint32_t count = imageLoad(inTxArrayPixelCounter, ivec3(gl_GlobalInvocationID.xy, 0)).r;

  bool have_count = count > 0;
  uint64_t roundSqrDiff = 0;

  #if USE_SUBGROUPS == 1

  if (have_count) {
    double mean = double(extents.totalNonZeroCount) / double(extents.numNonZeroCount);
    double diff = double(count) - mean;
    roundSqrDiff = uint64_t(round(diff * diff));
  }

  if (subgroupAny(have_count)) {
    uint64_t subgroup_sum = subgroupAdd(roundSqrDiff);
    if(subgroupElect()) {
      atomicAdd(extents.totalSqrDiff, subgroup_sum);
    }
  }

  #else // USE_SUBGROUPS

  if (count > 0) {
    double mean = double(extents.totalNonZeroCount) / double(extents.numNonZeroCount);
    double diff = double(count) - mean;
    uint64_t roundSqrDiff = uint64_t(round(diff * diff));
    atomicAdd(extents.totalSqrDiff, roundSqrDiff);
  }

  #endif // USE_SUBGROUPS
}
