/*
 * SPDX-FileCopyrightText: Copyright (c) 2022-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#define doMultiSample <doMultiSample>
#define numSamples <numSamples>
#define workgroupSize <workgroupSize>

uniform sampler2D[numSamples] srcRGBA;
uniform usampler2D srcIDA;
uniform usampler2D srcIDB;
uniform usampler2D srcResultCacheId;

#if doMultiSample == 1
layout (rgba8) uniform image2DMS outputColor;
layout (r32ui) uniform uimage2DMS outputIDA;
layout (r32ui) uniform uimage2DMS outputIDB;
layout (r32ui) uniform uimage2DMS outputResultCacheId;
#else
layout (rgba8) uniform image2D outputColor;
layout (r32ui) uniform uimage2D outputIDA;
layout (r32ui) uniform uimage2D outputIDB;
layout (r32ui) uniform uimage2D outputResultCacheId;
#endif

layout(std430) uniform MULTI_GPU_COMPOSITE_UBO_TYPE {
  int useIds;
  int shouldComp;
  uint32_t imageWidth;
  uint32_t imageHeight;
};

layout (local_size_x = workgroupSize, local_size_y = workgroupSize, local_size_z = 1) in;

void main() {
  ivec2 P = ivec2(gl_GlobalInvocationID.xy);
  if (P.x >= imageWidth || P.y >= imageHeight) {
    return;
  }

  bool have_ids = false;
  uint32_t id_a;
  uint32_t id_b;
  uint32_t result_cache_id;

  for (int s=0; s<numSamples; s++) {
    vec4 src_color = texelFetch(srcRGBA[s], P, 0);

    if (src_color.a > 0.0) {
      if (shouldComp == 1) {
#if doMultiSample == 1
        vec4 dst_color = imageLoad(outputColor, P, s);
#else
        vec4 dst_color = imageLoad(outputColor, P);
#endif
        dst_color = src_color + dst_color * (1.0 - src_color.a);
#if doMultiSample == 1
        imageStore(outputColor, P, s, dst_color);
#else
        imageStore(outputColor, P, dst_color);
#endif
      } else {
#if doMultiSample == 1
        imageStore(outputColor, P, s, src_color);
#else
        imageStore(outputColor, P, src_color);
#endif
      }

      if (!have_ids) {
        id_a = texelFetch(srcIDA, P, 0).r;
        id_b = texelFetch(srcIDB, P, 0).r;
        result_cache_id = texelFetch(srcResultCacheId, P, 0).r;
        have_ids = true;
      }

#if doMultiSample == 1
      imageStore(outputIDA, P, s, uvec4(id_a));
      imageStore(outputIDB, P, s, uvec4(id_b));
      imageStore(outputResultCacheId, P, s, uvec4(result_cache_id));
#else
      imageStore(outputIDA, P, uvec4(id_a));
      imageStore(outputIDB, P, uvec4(id_b));
      imageStore(outputResultCacheId, P, uvec4(result_cache_id));
#endif
    }
  }
}
