[ODBC Data Sources]
sqlite=sqlite
;TODO: Go back to postgis after test refactor
;postgis=postgis
postgres=postgres
redshift=redshift
snowflake=snowflake
hive=hive

[sqlite]
Description=SQLite Data Source
Driver=SQLite
Database=/odbc-fsi-src/Tests/FsiDataFiles/sqlite.db

;TODO: Go back to postgis after test refactor
;[postgis]
[postgres]
Description=PostGIS Data Source
Driver=PostgreSQL
Database=postgis
Servername=postgis
Port=5432
BoolsAsChar=false

[redshift]
Description=AWS Redshift
Driver=Redshift
Server=redshift-omnisci-cluster.cfae5971uxke.us-west-2.redshift.amazonaws.com
Database=fsi_test_db
Port=5439
BoolsAsChar=false

[snowflake]
Description=Snowflake Data Source
Driver=SnowFlake
Server=lqa26912.snowflakecomputing.com
Database=odbc_fsi_test
Role=odbc_fsi_test_all
Port=443
Warehouse=compute_wh

[bigquery]
Description=Google BigQuery Data Source
Driver=BigQuery
Catalog=mapd-engineering
SQLDialect=1
OAuthMechanism=0
Email=odbc-fsi-test@mapd-engineering.iam.gserviceaccount.com
KeyFilePath=/opt/simba/bigqueryodbc/credential/mapd-engineering-7bf8ff74a1b5.p12

[hive]
Description=Apache Hive Data Source
Driver=ApacheHive
HiveServerType=2
ServiceDiscoveryMode=0
Host=hive
Port=10000
UseNativeQuery=1

;TODO: HEAVY.AI (aka Omnisci) will be enabled when it is used
;[omnisci]
;Description=OmniSci Data Source
;Driver=/usr/lib/odbc-drivers/libOmniSciODBC.so
;Database=omnisci
;Host=omnisci
;Port=6274
