#define YY_Parser_h_included
#define YY_USE_CLASS

/*  A Bison++ parser, made from RelAlgebraParser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */

#define YY_USE_CLASS

#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#define YY_Parser_LSP_NEEDED 
#define YY_Parser_MEMBERS                  \
    virtual ~Parser()   {} \
    void parse(const string & inputStr, RelAlgNode *& parseRoot) { istringstream ss(inputStr); lexer.switch_streams(&ss,0);  yyparse(parseRoot); } \
    private:                   \
       yyFlexLexer lexer; 
#define YY_Parser_LEX_BODY  {return lexer.yylex();}
#define YY_Parser_ERROR_BODY  {cerr << "error encountered at line: "<<lexer.lineno()<<" last word parsed:"<<lexer.YYText()<<"\n";}
#line 11 "RelAlgebraParser.y"

#include <iostream>
#include <fstream>
#include <FlexLexer.h>
#include <cstdlib>
#include <string>
#include <sstream>
	
// RA nodes
#include "relAlg/RelAlgNode.h"
#include "relAlg/Program.h"
#include "relAlg/RelExprList.h"
#include "relAlg/RelExpr.h"
#include "relAlg/UnaryOp.h"
#include "relAlg/BinaryOp.h"
#include "relAlg/MathExpr.h"
#include "relAlg/SelectOp.h"
#include "relAlg/ProjectOp.h"
#include "relAlg/SortOp.h"
#include "relAlg/ExtendOp.h"
#include "relAlg/GroupByOp.h"
#include "relAlg/RenameOp.h"

#include "relAlg/JoinOp.h"
#include "relAlg/SemijoinOp.h"
#include "relAlg/ProductOp.h"
#include "relAlg/OuterjoinOp.h"
#include "relAlg/AntijoinOp.h"
#include "relAlg/UnionOp.h"
#include "relAlg/AggrExpr.h"
#include "relAlg/AggrList.h"
#include "relAlg/AttrList.h"
#include "relAlg/Attribute.h"
#include "relAlg/Relation.h"
#include "relAlg/Data.h"

#include "relAlg/Predicate.h"
#include "relAlg/Comparison.h"
#include "relAlg/Compared.h"
#include "relAlg/CompOp.h"

#include "visitor/Visitor.h"
#include "visitor/QPTranslator.h"
// define stack element type to be a 
// pointer to an AST node
	
#define YY_Parser_STYPE RelAlgNode*
#define YY_Parser_PARSE_PARAM RelAlgNode*& parseRoot

extern RelAlgNode* parse_root;


// Variables declared in RelAlgebraLexer.l
extern std::string strData[10];
extern int dData[5];

using namespace std;


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_Parser_BISON 1

#ifndef YY_Parser_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_Parser_COMPATIBILITY 1
 #else
  #define  YY_Parser_COMPATIBILITY 0
 #endif
#endif

#if YY_Parser_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_Parser_LTYPE
   #define YY_Parser_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_Parser_STYPE 
   #define YY_Parser_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_Parser_DEBUG
   #define  YY_Parser_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_Parser_USE_GOTO
  #define YY_Parser_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_Parser_USE_GOTO
 #define YY_Parser_USE_GOTO 0
#endif

#ifndef YY_Parser_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_Parser_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_Parser_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_Parser_DEBUG */
#endif


#ifndef YY_Parser_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_Parser_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_Parser_LSP_NEEDED
#ifndef YY_Parser_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_Parser_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_Parser_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_Parser_STYPE
#define YY_Parser_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_Parser_PARSE
#define YY_Parser_PARSE yyparse
#endif
#ifndef YY_Parser_LEX
#define YY_Parser_LEX yylex
#endif
#ifndef YY_Parser_LVAL
#define YY_Parser_LVAL yylval
#endif
#ifndef YY_Parser_LLOC
#define YY_Parser_LLOC yylloc
#endif
#ifndef YY_Parser_CHAR
#define YY_Parser_CHAR yychar
#endif
#ifndef YY_Parser_NERRS
#define YY_Parser_NERRS yynerrs
#endif
#ifndef YY_Parser_DEBUG_FLAG
#define YY_Parser_DEBUG_FLAG yydebug
#endif
#ifndef YY_Parser_ERROR
#define YY_Parser_ERROR yyerror
#endif

#ifndef YY_Parser_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_Parser_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_Parser_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_Parser_PARSE_PARAM
  #define YY_Parser_PARSE_PARAM void
 #endif
#endif

#if YY_Parser_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_Parser_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_Parser_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_Parser_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_Parser_PURE
#  ifndef YYPURE
#    define YYPURE YY_Parser_PURE
#  endif
#endif

#ifdef YY_Parser_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_Parser_DEBUG 
#  endif
#endif

#ifndef YY_Parser_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_Parser_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_Parser_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_Parser_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	PLUS	258
#define	MINUS	259
#define	MULTIPLY	260
#define	DIVIDE	261
#define	OR	262
#define	AND	263
#define	NOT	264
#define	NEQ	265
#define	EQ	266
#define	GT	267
#define	GTE	268
#define	LT	269
#define	LTE	270
#define	SELECT	271
#define	PROJECT	272
#define	SORT	273
#define	RENAME	274
#define	EXTEND	275
#define	GROUPBY	276
#define	PRODUCT	277
#define	JOIN	278
#define	SEMIJOIN	279
#define	ANTIJOIN	280
#define	OUTERJOIN	281
#define	UNION	282
#define	MAX	283
#define	MIN	284
#define	COUNT	285
#define	SUM	286
#define	AVG	287
#define	MAX_DISTINCT	288
#define	MIN_DISTINCT	289
#define	COUNT_DISTINCT	290
#define	SUM_DISTINCT	291
#define	AVG_DISTINCT	292
#define	NAME	293
#define	CONSTANT	294
#define	STRVAL	295


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_Parser_CLASS
#define YY_Parser_CLASS Parser
#endif
#ifndef YY_Parser_INHERIT
#define YY_Parser_INHERIT
#endif
#ifndef YY_Parser_MEMBERS
#define YY_Parser_MEMBERS 
#endif
#ifndef YY_Parser_LEX_BODY
#define YY_Parser_LEX_BODY  
#endif
#ifndef YY_Parser_ERROR_BODY
#define YY_Parser_ERROR_BODY  
#endif
#ifndef YY_Parser_CONSTRUCTOR_PARAM
#define YY_Parser_CONSTRUCTOR_PARAM
#endif
#ifndef YY_Parser_CONSTRUCTOR_CODE
#define YY_Parser_CONSTRUCTOR_CODE
#endif
#ifndef YY_Parser_CONSTRUCTOR_INIT
#define YY_Parser_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_Parser_USE_CONST_TOKEN
#define YY_Parser_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_Parser_USE_CONST_TOKEN != 0
#ifndef YY_Parser_ENUM_TOKEN
#define YY_Parser_ENUM_TOKEN yy_Parser_enum_token
#endif
#endif

class YY_Parser_CLASS YY_Parser_INHERIT
{
public: 
#if YY_Parser_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int PLUS;
static const int MINUS;
static const int MULTIPLY;
static const int DIVIDE;
static const int OR;
static const int AND;
static const int NOT;
static const int NEQ;
static const int EQ;
static const int GT;
static const int GTE;
static const int LT;
static const int LTE;
static const int SELECT;
static const int PROJECT;
static const int SORT;
static const int RENAME;
static const int EXTEND;
static const int GROUPBY;
static const int PRODUCT;
static const int JOIN;
static const int SEMIJOIN;
static const int ANTIJOIN;
static const int OUTERJOIN;
static const int UNION;
static const int MAX;
static const int MIN;
static const int COUNT;
static const int SUM;
static const int AVG;
static const int MAX_DISTINCT;
static const int MIN_DISTINCT;
static const int COUNT_DISTINCT;
static const int SUM_DISTINCT;
static const int AVG_DISTINCT;
static const int NAME;
static const int CONSTANT;
static const int STRVAL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_Parser_ENUM_TOKEN { YY_Parser_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,PLUS=258
	,MINUS=259
	,MULTIPLY=260
	,DIVIDE=261
	,OR=262
	,AND=263
	,NOT=264
	,NEQ=265
	,EQ=266
	,GT=267
	,GTE=268
	,LT=269
	,LTE=270
	,SELECT=271
	,PROJECT=272
	,SORT=273
	,RENAME=274
	,EXTEND=275
	,GROUPBY=276
	,PRODUCT=277
	,JOIN=278
	,SEMIJOIN=279
	,ANTIJOIN=280
	,OUTERJOIN=281
	,UNION=282
	,MAX=283
	,MIN=284
	,COUNT=285
	,SUM=286
	,AVG=287
	,MAX_DISTINCT=288
	,MIN_DISTINCT=289
	,COUNT_DISTINCT=290
	,SUM_DISTINCT=291
	,AVG_DISTINCT=292
	,NAME=293
	,CONSTANT=294
	,STRVAL=295


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_Parser_PARSE (YY_Parser_PARSE_PARAM);
 virtual void YY_Parser_ERROR(char *msg) YY_Parser_ERROR_BODY;
#ifdef YY_Parser_PURE
#ifdef YY_Parser_LSP_NEEDED
 virtual int  YY_Parser_LEX (YY_Parser_STYPE *YY_Parser_LVAL,YY_Parser_LTYPE *YY_Parser_LLOC) YY_Parser_LEX_BODY;
#else
 virtual int  YY_Parser_LEX (YY_Parser_STYPE *YY_Parser_LVAL) YY_Parser_LEX_BODY;
#endif
#else
 virtual int YY_Parser_LEX() YY_Parser_LEX_BODY;
 YY_Parser_STYPE YY_Parser_LVAL;
#ifdef YY_Parser_LSP_NEEDED
 YY_Parser_LTYPE YY_Parser_LLOC;
#endif
 int   YY_Parser_NERRS;
 int    YY_Parser_CHAR;
#endif
#if YY_Parser_DEBUG != 0
 int YY_Parser_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_Parser_CLASS(YY_Parser_CONSTRUCTOR_PARAM);
public:
 YY_Parser_MEMBERS 
};
/* other declare folow */
#if YY_Parser_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_Parser_CLASS::PLUS=258;
const int YY_Parser_CLASS::MINUS=259;
const int YY_Parser_CLASS::MULTIPLY=260;
const int YY_Parser_CLASS::DIVIDE=261;
const int YY_Parser_CLASS::OR=262;
const int YY_Parser_CLASS::AND=263;
const int YY_Parser_CLASS::NOT=264;
const int YY_Parser_CLASS::NEQ=265;
const int YY_Parser_CLASS::EQ=266;
const int YY_Parser_CLASS::GT=267;
const int YY_Parser_CLASS::GTE=268;
const int YY_Parser_CLASS::LT=269;
const int YY_Parser_CLASS::LTE=270;
const int YY_Parser_CLASS::SELECT=271;
const int YY_Parser_CLASS::PROJECT=272;
const int YY_Parser_CLASS::SORT=273;
const int YY_Parser_CLASS::RENAME=274;
const int YY_Parser_CLASS::EXTEND=275;
const int YY_Parser_CLASS::GROUPBY=276;
const int YY_Parser_CLASS::PRODUCT=277;
const int YY_Parser_CLASS::JOIN=278;
const int YY_Parser_CLASS::SEMIJOIN=279;
const int YY_Parser_CLASS::ANTIJOIN=280;
const int YY_Parser_CLASS::OUTERJOIN=281;
const int YY_Parser_CLASS::UNION=282;
const int YY_Parser_CLASS::MAX=283;
const int YY_Parser_CLASS::MIN=284;
const int YY_Parser_CLASS::COUNT=285;
const int YY_Parser_CLASS::SUM=286;
const int YY_Parser_CLASS::AVG=287;
const int YY_Parser_CLASS::MAX_DISTINCT=288;
const int YY_Parser_CLASS::MIN_DISTINCT=289;
const int YY_Parser_CLASS::COUNT_DISTINCT=290;
const int YY_Parser_CLASS::SUM_DISTINCT=291;
const int YY_Parser_CLASS::AVG_DISTINCT=292;
const int YY_Parser_CLASS::NAME=293;
const int YY_Parser_CLASS::CONSTANT=294;
const int YY_Parser_CLASS::STRVAL=295;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_Parser_CLASS::token */
#endif
/*apres const  */
YY_Parser_CLASS::YY_Parser_CLASS(YY_Parser_CONSTRUCTOR_PARAM) YY_Parser_CONSTRUCTOR_INIT
{
#if YY_Parser_DEBUG != 0
YY_Parser_DEBUG_FLAG=0;
#endif
YY_Parser_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		197
#define	YYFLAG		-32768
#define	YYNTBASE	48

#define YYTRANSLATE(x) ((unsigned)(x) <= 295 ? yytranslate[x] : 64)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    42,
    43,     2,     2,    44,     2,    47,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    41,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    45,     2,    46,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40
};

#if YY_Parser_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     3,     6,    10,    12,    14,    18,    20,    27,
    36,    43,    52,    61,    70,    81,    91,    98,   107,   116,
   125,   134,   141,   145,   149,   153,   157,   161,   163,   165,
   169,   174,   179,   184,   189,   194,   199,   204,   209,   214,
   219,   221,   225,   227,   231,   235,   239,   242,   246,   248,
   252,   254,   256,   258,   260,   262,   264,   266,   268,   270,
   272
};

static const short yyrhs[] = {    49,
     0,     0,    50,    41,     0,    49,    50,    41,     0,    51,
     0,    52,     0,    42,    50,    43,     0,    63,     0,    16,
    42,    50,    44,    58,    43,     0,    17,    42,    50,    44,
    45,    56,    46,    43,     0,    18,    42,    50,    44,    56,
    43,     0,    19,    42,    50,    44,    57,    44,    38,    43,
     0,    20,    42,    50,    44,    53,    44,    38,    43,     0,
    20,    42,    50,    44,    62,    44,    38,    43,     0,    21,
    42,    50,    44,    45,    56,    46,    44,    54,    43,     0,
    21,    42,    50,    44,    45,    46,    44,    54,    43,     0,
    22,    42,    50,    44,    50,    43,     0,    23,    42,    50,
    44,    50,    44,    58,    43,     0,    24,    42,    50,    44,
    50,    44,    58,    43,     0,    26,    42,    50,    44,    50,
    44,    58,    43,     0,    25,    42,    50,    44,    50,    44,
    58,    43,     0,    27,    42,    50,    44,    50,    43,     0,
    53,     3,    53,     0,    53,     4,    53,     0,    53,     5,
    53,     0,    53,     6,    53,     0,    42,    53,    43,     0,
    57,     0,    55,     0,    54,    44,    55,     0,    28,    42,
    57,    43,     0,    29,    42,    57,    43,     0,    30,    42,
    57,    43,     0,    31,    42,    57,    43,     0,    32,    42,
    57,    43,     0,    33,    42,    57,    43,     0,    34,    42,
    57,    43,     0,    35,    42,    57,    43,     0,    36,    42,
    57,    43,     0,    37,    42,    57,    43,     0,    57,     0,
    56,    44,    57,     0,    38,     0,    38,    47,    38,     0,
    58,     7,    58,     0,    58,     8,    58,     0,     9,    58,
     0,    42,    58,    43,     0,    59,     0,    61,    60,    61,
     0,    10,     0,    11,     0,    12,     0,    13,     0,    14,
     0,    15,     0,    57,     0,    62,     0,    39,     0,    40,
     0,    38,     0
};

#endif

#if (YY_Parser_DEBUG != 0) || defined(YY_Parser_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    88,    90,    93,    95,    98,   100,   101,   102,   105,   107,
   108,   109,   110,   111,   112,   113,   116,   118,   119,   120,
   121,   122,   125,   127,   128,   129,   130,   131,   134,   136,
   139,   141,   142,   143,   144,   145,   146,   147,   148,   149,
   152,   154,   157,   158,   161,   163,   164,   165,   166,   169,
   172,   174,   175,   176,   177,   178,   181,   183,   186,   188,
   198
};

static const char * const yytname[] = {   "$","error","$illegal.","PLUS","MINUS",
"MULTIPLY","DIVIDE","OR","AND","NOT","NEQ","EQ","GT","GTE","LT","LTE","SELECT",
"PROJECT","SORT","RENAME","EXTEND","GROUPBY","PRODUCT","JOIN","SEMIJOIN","ANTIJOIN",
"OUTERJOIN","UNION","MAX","MIN","COUNT","SUM","AVG","MAX_DISTINCT","MIN_DISTINCT",
"COUNT_DISTINCT","SUM_DISTINCT","AVG_DISTINCT","NAME","CONSTANT","STRVAL","';'",
"'('","')'","','","'{'","'}'","'.'","S","RelExprList","RelExpr","UnaryOp","BinaryOp",
"MathExpr","AggrList","AggrExpr","AttrList","attribute","Predicate","comparison",
"CompOp","compared","data","relation",""
};
#endif

static const short yyr1[] = {     0,
    48,    48,    49,    49,    50,    50,    50,    50,    51,    51,
    51,    51,    51,    51,    51,    51,    52,    52,    52,    52,
    52,    52,    53,    53,    53,    53,    53,    53,    54,    54,
    55,    55,    55,    55,    55,    55,    55,    55,    55,    55,
    56,    56,    57,    57,    58,    58,    58,    58,    58,    59,
    60,    60,    60,    60,    60,    60,    61,    61,    62,    62,
    63
};

static const short yyr2[] = {     0,
     1,     0,     2,     3,     1,     1,     3,     1,     6,     8,
     6,     8,     8,     8,    10,     9,     6,     8,     8,     8,
     8,     6,     3,     3,     3,     3,     3,     1,     1,     3,
     4,     4,     4,     4,     4,     4,     4,     4,     4,     4,
     1,     3,     1,     3,     3,     3,     2,     3,     1,     3,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1
};

static const short yydefact[] = {     2,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    61,     0,     1,     0,     5,     6,     8,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     3,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     7,     4,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    43,    59,    60,     0,    57,     0,    49,     0,    58,
     0,     0,    41,     0,     0,     0,    28,     0,     0,     0,
     0,     0,     0,     0,     0,    47,     0,     0,     0,     0,
     9,    51,    52,    53,    54,    55,    56,     0,     0,    11,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    17,     0,     0,     0,     0,    22,    44,    48,    45,
    46,    50,     0,    42,     0,    27,    23,    24,    25,    26,
     0,     0,     0,     0,     0,     0,     0,     0,    10,    12,
    13,    14,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    29,     0,    18,    19,    21,    20,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,    16,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    30,    15,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    40,     0,     0,     0
};

static const short yydefgoto[] = {   195,
    15,    16,    17,    18,    76,   153,   154,    72,    66,    67,
    68,    98,    69,    70,    19
};

static const short yypact[] = {   107,
   -39,    66,    93,    94,    95,    96,    97,    98,    99,   100,
   101,   102,-32768,   107,   107,    25,-32768,-32768,-32768,   107,
   107,   107,   107,   107,   107,   107,   107,   107,   107,   107,
   107,    39,   105,-32768,   103,   104,   116,   117,   118,   119,
   120,   121,   123,   124,   125,   126,-32768,-32768,    56,    55,
   128,   128,   -17,   127,   107,   107,   107,   107,   107,   107,
    56,   129,-32768,-32768,    56,-32768,     9,-32768,    78,-32768,
   128,   -25,-32768,   130,   -34,     7,-32768,   131,   -32,   134,
   135,   136,   137,   138,   140,-32768,   133,    24,    56,    56,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    67,    53,-32768,
   128,   146,    58,   -34,   -34,   -34,   -34,   147,   148,   143,
    75,-32768,    56,    56,    56,    56,-32768,-32768,-32768,   165,
-32768,-32768,   145,-32768,   149,-32768,    21,    21,-32768,-32768,
   150,   151,   122,   152,    40,    61,    77,    79,-32768,-32768,
-32768,-32768,   153,   155,   156,   157,   158,   159,   160,   161,
   162,   163,    33,-32768,   122,-32768,-32768,-32768,-32768,   128,
   128,   128,   128,   128,   128,   128,   128,   128,   128,-32768,
   122,    59,   164,   166,   167,   168,   169,   170,   171,   172,
   173,   174,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   178,   189,-32768
};

static const short yypgoto[] = {-32768,
-32768,    15,-32768,-32768,   -26,    35,    20,   -64,   -51,   -56,
-32768,-32768,   108,   175,-32768
};


#define	YYLAST		228


static const short yytable[] = {    73,
    74,    77,    20,    62,    86,    62,    99,    75,    88,   104,
   105,   106,   107,   110,   111,    89,    90,   100,   101,    73,
    62,    63,    64,    77,    75,   106,   107,    73,    32,    33,
    89,    90,   120,   121,    35,    36,    37,    38,    39,    40,
    41,    42,    43,    44,    45,    46,    89,    90,   103,   124,
   108,    91,    77,    77,    77,    77,   135,   136,   137,   138,
   104,   105,   106,   107,    61,    34,   119,    89,    90,    80,
    81,    82,    83,    84,    85,   170,   171,   127,   128,   129,
   130,    47,   156,    89,    90,    89,    90,    92,    93,    94,
    95,    96,    97,    62,    63,    64,   101,    65,   123,    71,
   126,   184,   171,   157,    62,    63,    64,    21,   173,   174,
   175,   176,   177,   178,   179,   180,   181,   182,   101,   158,
   134,   159,     1,     2,     3,     4,     5,     6,     7,     8,
     9,    10,    11,    12,    22,    23,    24,    25,    26,    27,
    28,    29,    30,    31,    13,    48,    49,    50,    14,   143,
   144,   145,   146,   147,   148,   149,   150,   151,   152,    51,
    52,    53,    54,    55,    56,    62,    57,    58,    59,    60,
   118,    79,    90,   102,   109,    87,   112,   196,   113,   114,
   115,   116,   117,   125,   131,   132,   133,   139,   197,   172,
   183,   140,   141,   142,   160,   155,   161,   162,   163,   164,
   165,   166,   167,   168,   169,   122,   185,     0,   186,   187,
   188,   189,   190,   191,   192,   193,   194,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,    78
};

static const short yycheck[] = {    51,
    52,    53,    42,    38,    61,    38,    71,    42,    65,     3,
     4,     5,     6,    46,    79,     7,     8,    43,    44,    71,
    38,    39,    40,    75,    42,     5,     6,    79,    14,    15,
     7,     8,    89,    90,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,     7,     8,    75,   101,
    44,    43,   104,   105,   106,   107,   113,   114,   115,   116,
     3,     4,     5,     6,     9,    41,    43,     7,     8,    55,
    56,    57,    58,    59,    60,    43,    44,   104,   105,   106,
   107,    43,    43,     7,     8,     7,     8,    10,    11,    12,
    13,    14,    15,    38,    39,    40,    44,    42,    46,    45,
    43,    43,    44,    43,    38,    39,    40,    42,   160,   161,
   162,   163,   164,   165,   166,   167,   168,   169,    44,    43,
    46,    43,    16,    17,    18,    19,    20,    21,    22,    23,
    24,    25,    26,    27,    42,    42,    42,    42,    42,    42,
    42,    42,    42,    42,    38,    41,    44,    44,    42,    28,
    29,    30,    31,    32,    33,    34,    35,    36,    37,    44,
    44,    44,    44,    44,    44,    38,    44,    44,    44,    44,
    38,    45,     8,    44,    44,    47,    43,     0,    44,    44,
    44,    44,    43,    38,    38,    38,    44,    43,     0,   155,
   171,    43,    43,    43,    42,    44,    42,    42,    42,    42,
    42,    42,    42,    42,    42,    98,    43,    -1,    43,    43,
    43,    43,    43,    43,    43,    43,    43,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    53
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_Parser_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_Parser_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_Parser_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_Parser_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_Parser_CHAR = (token), YY_Parser_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_Parser_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_Parser_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_Parser_PURE
/* UNPURE */
#define YYLEX           YY_Parser_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_Parser_CHAR;                      /*  the lookahead symbol        */
YY_Parser_STYPE      YY_Parser_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_Parser_NERRS;                 /*  number of parse errors so far */
#ifdef YY_Parser_LSP_NEEDED
YY_Parser_LTYPE YY_Parser_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_Parser_LSP_NEEDED
#define YYLEX           YY_Parser_LEX(&YY_Parser_LVAL, &YY_Parser_LLOC)
#else
#define YYLEX           YY_Parser_LEX(&YY_Parser_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_Parser_DEBUG != 0
int YY_Parser_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_Parser_CLASS::
#endif
     YY_Parser_PARSE(YY_Parser_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_Parser_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_Parser_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_Parser_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_Parser_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_Parser_LSP_NEEDED
  YY_Parser_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_Parser_LTYPE *yyls = yylsa;
  YY_Parser_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_Parser_PURE
  int YY_Parser_CHAR;
  YY_Parser_STYPE YY_Parser_LVAL;
  int YY_Parser_NERRS;
#ifdef YY_Parser_LSP_NEEDED
  YY_Parser_LTYPE YY_Parser_LLOC;
#endif
#endif

  YY_Parser_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_Parser_DEBUG != 0
  if (YY_Parser_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_Parser_NERRS = 0;
  YY_Parser_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_Parser_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_Parser_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_Parser_LSP_NEEDED
      YY_Parser_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_Parser_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_Parser_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_Parser_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_Parser_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_Parser_LSP_NEEDED
      yyls = (YY_Parser_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_Parser_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_Parser_DEBUG != 0
      if (YY_Parser_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_Parser_DEBUG != 0
  if (YY_Parser_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_Parser_CHAR == YYEMPTY)
    {
#if YY_Parser_DEBUG != 0
      if (YY_Parser_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_Parser_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_Parser_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_Parser_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_Parser_DEBUG != 0
      if (YY_Parser_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_Parser_CHAR);

#if YY_Parser_DEBUG != 0
      if (YY_Parser_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_Parser_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_Parser_CHAR, YY_Parser_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_Parser_DEBUG != 0
  if (YY_Parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_Parser_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_Parser_CHAR != YYEOF)
    YY_Parser_CHAR = YYEMPTY;

  *++yyvsp = YY_Parser_LVAL;
#ifdef YY_Parser_LSP_NEEDED
  *++yylsp = YY_Parser_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_Parser_DEBUG != 0
  if (YY_Parser_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 89 "RelAlgebraParser.y"
{ yyval = new Program((RelExprList*)yyvsp[0]); parseRoot = yyval; ;
    break;}
case 2:
#line 90 "RelAlgebraParser.y"
{ yyval = 0; parseRoot = yyval; ;
    break;}
case 3:
#line 94 "RelAlgebraParser.y"
{ yyval = new RelExprList((RelExpr*)yyvsp[-1]); ;
    break;}
case 4:
#line 95 "RelAlgebraParser.y"
{ yyval = new RelExprList((RelExprList*)yyvsp[-2], (RelExpr*)yyvsp[0]); ;
    break;}
case 5:
#line 99 "RelAlgebraParser.y"
{ yyval = new RelExpr((UnaryOp*)yyvsp[0]); ;
    break;}
case 6:
#line 100 "RelAlgebraParser.y"
{ yyval = new RelExpr((BinaryOp*)yyvsp[0]); ;
    break;}
case 7:
#line 101 "RelAlgebraParser.y"
{ yyval = new RelExpr((RelExpr*)yyvsp[-1]); ;
    break;}
case 8:
#line 102 "RelAlgebraParser.y"
{ yyval = new RelExpr((Relation*)yyvsp[0]); ;
    break;}
case 9:
#line 106 "RelAlgebraParser.y"
{ yyval = new SelectOp((RelExpr*)yyvsp[-3], (Predicate*)yyvsp[-1]); ;
    break;}
case 10:
#line 107 "RelAlgebraParser.y"
{ yyval = new ProjectOp((RelExpr*)yyvsp[-5], (AttrList*)yyvsp[-2]); ;
    break;}
case 11:
#line 108 "RelAlgebraParser.y"
{ yyval = new SortOp((RelExpr*)yyvsp[-3], (AttrList*)yyvsp[-1]); ;
    break;}
case 12:
#line 109 "RelAlgebraParser.y"
{ yyval = new RenameOp((RelExpr*)yyvsp[-5], (Attribute*)yyvsp[-3], strData[0]); ;
    break;}
case 13:
#line 110 "RelAlgebraParser.y"
{ yyval = new ExtendOp((RelExpr*)yyvsp[-5], (MathExpr*)yyvsp[-3], strData[0]); ;
    break;}
case 14:
#line 111 "RelAlgebraParser.y"
{ yyval = new ExtendOp((RelExpr*)yyvsp[-5], (Data*)yyvsp[-3], strData[0]); ;
    break;}
case 15:
#line 112 "RelAlgebraParser.y"
{ yyval = new GroupByOp((RelExpr*)yyvsp[-7], (AttrList*)yyvsp[-4], (AggrList*)yyvsp[-1]); ;
    break;}
case 16:
#line 113 "RelAlgebraParser.y"
{ yyval = new GroupByOp((RelExpr*)yyvsp[-6], (AggrList*)yyvsp[-1]); ;
    break;}
case 17:
#line 117 "RelAlgebraParser.y"
{ yyval = new ProductOp((RelExpr*)yyvsp[-3], (RelExpr*)yyvsp[-1]); ;
    break;}
case 18:
#line 118 "RelAlgebraParser.y"
{ yyval = new JoinOp((RelExpr*)yyvsp[-5], (RelExpr*)yyvsp[-3], (Predicate*)yyvsp[-1]); ;
    break;}
case 19:
#line 119 "RelAlgebraParser.y"
{ yyval = new SemijoinOp((RelExpr*)yyvsp[-5], (RelExpr*)yyvsp[-3], (Predicate*)yyvsp[-1]); ;
    break;}
case 20:
#line 120 "RelAlgebraParser.y"
{ yyval = new OuterjoinOp((RelExpr*)yyvsp[-5], (RelExpr*)yyvsp[-3], (Predicate*)yyvsp[-1]); ;
    break;}
case 21:
#line 121 "RelAlgebraParser.y"
{ yyval = new AntijoinOp((RelExpr*)yyvsp[-5], (RelExpr*)yyvsp[-3], (Predicate*)yyvsp[-1]); ;
    break;}
case 22:
#line 122 "RelAlgebraParser.y"
{ yyval = new UnionOp((RelExpr*)yyvsp[-3], (RelExpr*)yyvsp[-1]); ;
    break;}
case 23:
#line 126 "RelAlgebraParser.y"
{ yyval = new MathExpr(0, (MathExpr*)yyvsp[-2], (MathExpr*)yyvsp[0]); ;
    break;}
case 24:
#line 127 "RelAlgebraParser.y"
{ yyval = new MathExpr(0, (MathExpr*)yyvsp[-2], (MathExpr*)yyvsp[0]); ;
    break;}
case 25:
#line 128 "RelAlgebraParser.y"
{ yyval = new MathExpr(0, (MathExpr*)yyvsp[-2], (MathExpr*)yyvsp[0]); ;
    break;}
case 26:
#line 129 "RelAlgebraParser.y"
{ yyval = new MathExpr(0, (MathExpr*)yyvsp[-2], (MathExpr*)yyvsp[0]); ;
    break;}
case 27:
#line 130 "RelAlgebraParser.y"
{ yyval = new MathExpr((MathExpr*)yyvsp[-1]); ;
    break;}
case 28:
#line 131 "RelAlgebraParser.y"
{ yyval = new MathExpr((Attribute*)yyvsp[0]); ;
    break;}
case 29:
#line 135 "RelAlgebraParser.y"
{ yyval = new AggrList((AggrExpr*)yyvsp[0]); ;
    break;}
case 30:
#line 136 "RelAlgebraParser.y"
{ yyval = new AggrList((AggrList*)yyvsp[-2], (AggrExpr*)yyvsp[0]); ;
    break;}
case 31:
#line 140 "RelAlgebraParser.y"
{ yyval = new AggrExpr(0, 0, (Attribute*)yyvsp[-1]); ;
    break;}
case 32:
#line 141 "RelAlgebraParser.y"
{ yyval = new AggrExpr(1, 0, (Attribute*)yyvsp[-1]); ;
    break;}
case 33:
#line 142 "RelAlgebraParser.y"
{ yyval = new AggrExpr(2, 0, (Attribute*)yyvsp[-1]); ;
    break;}
case 34:
#line 143 "RelAlgebraParser.y"
{ yyval = new AggrExpr(3, 0, (Attribute*)yyvsp[-1]); ;
    break;}
case 35:
#line 144 "RelAlgebraParser.y"
{ yyval = new AggrExpr(4, 0, (Attribute*)yyvsp[-1]); ;
    break;}
case 36:
#line 145 "RelAlgebraParser.y"
{ yyval = new AggrExpr(0, 1, (Attribute*)yyvsp[-1]); ;
    break;}
case 37:
#line 146 "RelAlgebraParser.y"
{ yyval = new AggrExpr(1, 1, (Attribute*)yyvsp[-1]); ;
    break;}
case 38:
#line 147 "RelAlgebraParser.y"
{ yyval = new AggrExpr(2, 1, (Attribute*)yyvsp[-1]); ;
    break;}
case 39:
#line 148 "RelAlgebraParser.y"
{ yyval = new AggrExpr(3, 1, (Attribute*)yyvsp[-1]); ;
    break;}
case 40:
#line 149 "RelAlgebraParser.y"
{ yyval = new AggrExpr(4, 1, (Attribute*)yyvsp[-1]); ;
    break;}
case 41:
#line 153 "RelAlgebraParser.y"
{ yyval = new AttrList((Attribute*)yyvsp[0]); ;
    break;}
case 42:
#line 154 "RelAlgebraParser.y"
{ yyval = new AttrList((AttrList*)yyvsp[-2], (Attribute*)yyvsp[0]); ;
    break;}
case 43:
#line 157 "RelAlgebraParser.y"
{ yyval = new Attribute(strData[0]); ;
    break;}
case 44:
#line 158 "RelAlgebraParser.y"
{ yyval = new Attribute(strData[0], strData[1]); ;
    break;}
case 45:
#line 162 "RelAlgebraParser.y"
{ yyval = new Predicate(0, (Predicate*)yyvsp[-2], (Predicate*)yyvsp[0]); ;
    break;}
case 46:
#line 163 "RelAlgebraParser.y"
{ yyval = new Predicate(1, (Predicate*)yyvsp[-2], (Predicate*)yyvsp[0]); ;
    break;}
case 47:
#line 164 "RelAlgebraParser.y"
{ yyval = new Predicate(2, (Predicate*)yyvsp[0]); ;
    break;}
case 48:
#line 165 "RelAlgebraParser.y"
{ yyval = new Predicate(3, (Predicate*)yyvsp[-1]); ;
    break;}
case 49:
#line 166 "RelAlgebraParser.y"
{ yyval = new Predicate((Comparison*)yyvsp[0]); ;
    break;}
case 50:
#line 169 "RelAlgebraParser.y"
{ yyval = new Comparison((Compared*)yyvsp[-2], (CompOp*)yyvsp[-1], (Compared*)yyvsp[0]); ;
    break;}
case 51:
#line 173 "RelAlgebraParser.y"
{ yyval = new CompOp("NEQ"); ;
    break;}
case 52:
#line 174 "RelAlgebraParser.y"
{ yyval = new CompOp("EQ"); ;
    break;}
case 53:
#line 175 "RelAlgebraParser.y"
{ yyval = new CompOp("GT"); ;
    break;}
case 54:
#line 176 "RelAlgebraParser.y"
{ yyval = new CompOp("GTE"); ;
    break;}
case 55:
#line 177 "RelAlgebraParser.y"
{ yyval = new CompOp("LT"); ;
    break;}
case 56:
#line 178 "RelAlgebraParser.y"
{ yyval = new CompOp("LTE"); ;
    break;}
case 57:
#line 182 "RelAlgebraParser.y"
{ yyval = new Compared((Attribute*)yyvsp[0]); ;
    break;}
case 58:
#line 183 "RelAlgebraParser.y"
{ yyval = new Compared((Data*)yyvsp[0]); ;
    break;}
case 59:
#line 187 "RelAlgebraParser.y"
{ yyval = new Data(dData[0]); ;
    break;}
case 60:
#line 188 "RelAlgebraParser.y"
{ yyval = new Data(strData[0]); ;
    break;}
case 61:
#line 199 "RelAlgebraParser.y"
{ yyval = new Relation(strData[0]); ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_Parser_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_Parser_DEBUG != 0
  if (YY_Parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_Parser_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_Parser_LLOC.first_line;
      yylsp->first_column = YY_Parser_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_Parser_NERRS;

#ifdef YY_Parser_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_Parser_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_Parser_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_Parser_ERROR_VERBOSE */
	YY_Parser_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_Parser_CHAR == YYEOF)
	YYABORT;

#if YY_Parser_DEBUG != 0
      if (YY_Parser_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_Parser_CHAR, yytname[yychar1]);
#endif

      YY_Parser_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_Parser_LSP_NEEDED
  yylsp--;
#endif

#if YY_Parser_DEBUG != 0
  if (YY_Parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_Parser_DEBUG != 0
  if (YY_Parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_Parser_LVAL;
#ifdef YY_Parser_LSP_NEEDED
  *++yylsp = YY_Parser_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 202 "RelAlgebraParser.y"


RelAlgNode *parse_root = 0;

int main() {

    string sql;
    cout << "Enter sql statement: ";
    getline(cin,sql);

    RelAlgNode *parseRoot = 0;
	Parser parser;
	parser.parse(sql, parseRoot);

	if (parseRoot != 0) cout << "parsed successfully, yo\n";
	QPTranslator qp;
    if (parseRoot != 0)
        parseRoot->accept(qp); 

	return 0;
}