/*
 * SPDX-FileCopyrightText: Copyright (c) 2021-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "Tests/RenderTests/GfxDriver/GfxDriverTestFixtures.h"

#include <memory>
#include <random>
#include <string>

#include "GfxDriver/Drivers/Vulkan/VulkanPlatform.h"
#include "GfxDriver/Pipeline/Material.h"
#include "GfxDriver/Pipeline/Pipeline.h"
#include "GfxDriver/Pipeline/PipelineDescriptor.h"
#include "GfxDriver/Resources/Texture.h"
#include "GfxDriver/Resources/VertexBuffer.h"
#include "GfxDriver/ShaderCompiler/Library.h"
#include "GfxDriver/ShaderCompiler/ShaderManager.h"
#include "Shared/measure.h"
#include "Tests/RenderTests/Utils/AttachmentUtils.h"
#include "Tests/RenderTests/Utils/GoldenImage.h"
#include "Tests/RenderTests/Utils/MeshUtils.h"
#include "Tests/RenderTests/Utils/PPLLUtils.h"
#include "Tests/RenderTests/Utils/ShaderUtils.h"
#include "Tests/TestHelpers.h"

/**
 * PPLLTests
 *
 * - Shader files can be added using the ShaderManifest.json file
 *   in the path specified by g_shaders_path
 *
 * - All images using PPLLTestBase can be regenerated by enabling
 *   kRegenerateGoldenImages below
 *
 * */
namespace GfxDriverTests {

// Flag to force writing of all golden image files
static constexpr bool kRegenerateGoldenImages = false;

// File paths
namespace {
static std::string g_golden_images_path(std::string(RENDER_TESTS_PATH) +
                                        "PPLL/golden_images/");
static std::string g_shaders_path(std::string(RENDER_TESTS_PATH) + "PPLL/shaders/");

static std::string_view kFlushName{"PPLLTest"};
}  // namespace

//
// PPLLTestShaderLibrary
//
class PPLLTestShaderLibrary {
 public:
  static void init(Library& library) {
    library.addFromManifestFile("ShaderManifest.json", g_shaders_path);
  }
};

//
// PPLLTestBase fixture template
//
template <typename GTEST_BASE,
          typename DRIVER_TYPE,
          typename SHADER_LIBRARY = PPLLTestShaderLibrary>
class PPLLTestBase : public DeviceContextTest<GTEST_BASE, DRIVER_TYPE, SHADER_LIBRARY> {
 protected:
  using Base = DeviceContextTest<GTEST_BASE, DRIVER_TYPE, SHADER_LIBRARY>;

  void SetUp() override {
    Base::SetUp();
    golden_image_ = std::make_unique<GoldenImage>(
        g_golden_images_path, this->driver_->getType(), kRegenerateGoldenImages);
  }
  void TearDown() override { Base::TearDown(); }

  std::unique_ptr<GoldenImage> golden_image_;
};

using VulkanPPLLTest = PPLLTestBase<::testing::Test, VulkanDriver>;

#define USE_TYPED_TEST 0

#if USE_TYPED_TEST
template <typename DRIVER_TYPE>
using TypedPPLLTest = PPLLTestBase<::testing::Test, DRIVER_TYPE, PPLLTestShaderLibrary>;
TYPED_TEST_SUITE(TypedPPLLTest, DriverTypes);
#else
using UntypedPPLLTest = VulkanPPLLTest;
#endif

//
// PPLL tests
//
namespace {
struct FragmentStats {
  uint64_t total_fragments;
  uint32_t num_nonzero_count;
  uint32_t min_fragments;
  uint32_t max_fragments;
  FragmentStats() { reset(); }
  void reset() {
    total_fragments = 0ull;
    num_nonzero_count = 0u;
    min_fragments = std::numeric_limits<uint32_t>::max();
    max_fragments = 0u;
  }
  void print() {
    std::cout << "total_fragments: " << total_fragments << std::endl;
    std::cout << "num_nonzero_count: " << num_nonzero_count << std::endl;
    std::cout << "min_fragments: " << min_fragments << std::endl;
    std::cout << "max_fragments: " << max_fragments << std::endl;
  }
};
}  // namespace

#if USE_TYPED_TEST
TYPED_TEST(TypedPPLLTest, CountFragmentsTest) {
#else
TEST_F(UntypedPPLLTest, CountFragmentsTest) {
#endif

  auto& device = *this->device_contexts_[0];
  auto& resource_mgr = device.getResourceManager();
  auto& shader_mgr = this->gfx_context_->getShaderManager();

  static constexpr uint32_t kWidth = 2048;
  static constexpr uint32_t kHeight = 1200;
  static constexpr uint32_t kNumSpheres = 5000;
  static constexpr float kMaxDepth = 6.0f;
  static constexpr bool kLogStats = false;
  static constexpr bool kWriteImage = false;

  const uint32_t subgroup_size = device.getLimits().subgroup_size;

  MaterialUqPtr draw_material;
  MaterialUqPtr comp_material;
  MaterialUqPtr comp_ref_material;

  // Material for draw pass to generate per pixel counts
  {
    auto caches = shader_mgr.createCacheVectorFromTemplate(
        {{"PPLLTests/countFragmentsTest_accum.vert"},
         {"PPLLTests/countFragmentsTest_accum.frag"}});
    ASSERT_TRUE(validate_shader_caches(caches));

    draw_material = resource_mgr.createMaterial("Test", caches);
    ASSERT_NE(draw_material, nullptr);
  }

  // Compute pass "material" (reference)
  {
    auto builders =
        shader_mgr.createBuilderVector({{"PPLLTests/countFragmentsTest_reference.comp"}});
    builders[0]->replaceAllTags("workgroupSize", std::to_string(subgroup_size));
    auto caches = shader_mgr.createCacheVector(std::move(builders));
    ASSERT_TRUE(validate_shader_caches(caches));

    comp_ref_material = resource_mgr.createMaterial("Test", caches);
    ASSERT_NE(comp_ref_material, nullptr);
  }

  // Compute pass "material" (subgroups)
  DeviceCapabilityBits subgroup_required_bits =
      DeviceCapabilityBits::kSubgroupArithmetic | DeviceCapabilityBits::kSubgroupVote |
      DeviceCapabilityBits::kSubgroupBallot;

  if ((device.getCapabilityBits() & subgroup_required_bits) == subgroup_required_bits) {
    auto builders =
        shader_mgr.createBuilderVector({{"PPLLTests/countFragmentsTest_subgroups.comp"}});
    builders[0]->replaceAllTags("workgroupSize", std::to_string(subgroup_size));
    auto caches = shader_mgr.createCacheVector(std::move(builders));
    ASSERT_TRUE(validate_shader_caches(caches));

    comp_material = resource_mgr.createMaterial("Test", caches);
    ASSERT_NE(comp_material, nullptr);
  }

  // renderpass and framebuffer
  static gfx::AttachmentManager empty_attachment_mgr;
  auto empty_render_pass =
      resource_mgr.createRenderPass("Empty", empty_attachment_mgr.getLayout());

  ASSERT_NE(empty_render_pass, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer(
      "Test", *empty_render_pass, empty_attachment_mgr, kWidth, kHeight, 1u);
  ASSERT_NE(framebuffer, nullptr);

  // sphere mesh
  auto mesh = build_uv_sphere(20, 10);
  auto [buffer_layout, vertex_buffer_wrapper, index_buffer_wrapper] =
      mesh->buildResources(resource_mgr, "Test");

  auto* vertex_buffer = static_cast<VertexBuffer*>(vertex_buffer_wrapper.get());
  auto* index_buffer = static_cast<IndexBuffer*>(index_buffer_wrapper.get());

  PrimitiveAssemblyAttrInfo attr_info = {{vertex_buffer, buffer_layout},
                                         {{"in_position", "in_position"}}};

  // pipelines
  auto primitive_assembly = resource_mgr.createPrimitiveAssembly(
      "Test", PrimitiveTopology::kTriangleList, *draw_material, attr_info, index_buffer);
  ASSERT_NE(primitive_assembly, nullptr);

  PipelineDescriptor pipeline_desc;
  auto draw_pipeline = resource_mgr.createGraphicsPipeline(
      "Test", *draw_material, pipeline_desc, primitive_assembly.get());
  ASSERT_NE(draw_pipeline, nullptr);
  draw_pipeline->create(*empty_render_pass);

  auto comp_pipeline = resource_mgr.createComputePipeline("Test", *comp_material);
  ASSERT_NE(comp_pipeline, nullptr);
  comp_pipeline->create();

  auto comp_ref_pipeline = resource_mgr.createComputePipeline("Test", *comp_ref_material);
  ASSERT_NE(comp_ref_pipeline, nullptr);
  comp_ref_pipeline->create();

  // storage image
  auto storage_image = resource_mgr.createTexture(
      "Test",
      kWidth,
      kHeight,
      1,
      PixelFormat::kR32UI,
      1,
      false,
      ImageUsageBits::kStorageBit,
      get_default_sampler_state_for_format(PixelFormat::kR32UI));
  ASSERT_NE(storage_image, nullptr);

  // Clear pixels and implicit transition to general layout
  storage_image->clearPixels();

  std::vector<float> host_buffer(kNumSpheres * 4);
  std::mt19937 pos_gen(1);
  std::uniform_real_distribution<float> pos_dis(-1.0f, 1.0f);
  float z = -2.0f;
  float z_step = -(kMaxDepth - 2.0f) / kNumSpheres;
  uint64_t vi = 0;
  for (uint32_t i = 0; i < kNumSpheres; ++i, vi += 4, z += z_step) {
    host_buffer[vi + 0] = pos_dis(pos_gen);  // x
    host_buffer[vi + 1] = pos_dis(pos_gen);  // y
    host_buffer[vi + 2] = z;                 // z
    host_buffer[vi + 3] = 0.1f;              // scale
  }

  uint64_t buffer_size = kNumSpheres * sizeof(float) * 4;  // vec4 per sphere
  auto indir_draw_buffer = resource_mgr.createBuffer(
      "Test",
      {BufferType::kUnspecified, buffer_size, BufferUsageBits::kStorageBufferBit});
  CHECK(indir_draw_buffer);
  indir_draw_buffer->updateSubData(host_buffer.data(), buffer_size, 0);

  // Buffer for global stats
  auto stats_buffer = resource_mgr.createBuffer("Stats",
                                                {gfx::BufferType::kUnspecified,
                                                 sizeof(FragmentStats),
                                                 BufferUsageBits::kStorageBufferBit});
  CHECK(stats_buffer);

  draw_material->bindShaderStorageBufferToBlock("PPLL_TEST_SSBO_TYPE",
                                                *indir_draw_buffer);

  draw_material->setImageLoadStoreAttribute("fragment_count_image", *storage_image);

  // static uniforms
  mat4x4 view_tm;
  view_tm.perspective(kWidth, kHeight, 40.0f, 0.01f, kMaxDepth);
  draw_material->setUniformAttribute("viewTM", view_tm);

  draw_material->updateDescriptorSets();

  device.getCommandExecutor().setDefaultViewportAndRenderArea(0, 0, kWidth, kHeight);

  // Command list
  auto& cmd_list = device.getCommandList();

  auto draw_begin = timer_start();
  // draw sphere instances
  if constexpr (kLogStats) {
    std::cout << "num sphere triangles: " << mesh->numTriangles() << std::endl;
    std::cout << "total triangles: " << mesh->numTriangles() * kNumSpheres << std::endl;
  }
  cmd_list.beginRenderPass(*empty_render_pass, *framebuffer)
      .drawIndexed(*draw_pipeline,
                   *vertex_buffer,
                   *index_buffer,
                   mesh->numIndices(),
                   0,
                   0,
                   kNumSpheres)
      .endRenderPass()
      .flush(kFlushName, CommandList::SubmitType::kWaitComplete);

  if constexpr (kLogStats) {
    auto const draw_time = timer_stop(draw_begin);
    std::cout << "render time: " << draw_time << " (ms)" << std::endl;
  }

  // Save image
  if constexpr (kWriteImage) {
    this->golden_image_->write(*storage_image, "count_fragments");
  }

  //
  // Run the compute shaders
  //
  std::array<uint32_t, 2> dimensions{kWidth, kHeight};

  auto run_compute_shader = [&](Material& material,
                                Pipeline& pipeline,
                                FragmentStats& stats) {
    material.bindShaderStorageBufferToBlock("PPLL_TEST_COUNTERS_SSBO", *stats_buffer);
    material.setImageLoadStoreAttribute("fragment_count_image", *storage_image);

    ASSERT_NO_THROW(material.setUniformAttribute("image_size", dimensions));

    material.updateDescriptorSets();
    uint64_t total_time = 0ull;
    static constexpr uint32_t kLoopCount = kLogStats ? 100u : 1u;
    for (uint32_t i = 0; i < kLoopCount; ++i) {
      // clear the stats buffer
      stats.reset();
      stats_buffer->updateSubData(&stats, sizeof(FragmentStats), 0ull);

      auto compute_begin = timer_start();

      cmd_list
          .dispatchCompute(
              pipeline, 0u, (kWidth + subgroup_size) / subgroup_size, kHeight, 1u)
          .flush(kFlushName);

      auto const compute_time =
          timer_stop<std::chrono::steady_clock::time_point, std::chrono::microseconds>(
              compute_begin);
      total_time += compute_time;
    }
    stats.reset();
    stats_buffer->getData(&stats, sizeof(FragmentStats));

    if constexpr (kLogStats) {
      std::cout << "avg compute time: " << total_time / kLoopCount << " (us)"
                << std::endl;
      stats.print();
    }
  };

  // clear the stats buffer
  FragmentStats stats_ref;
  stats_buffer->updateSubData(&stats_ref, sizeof(FragmentStats), 0ull);

  if constexpr (kLogStats) {
    std::cout << "------------" << std::endl;
    std::cout << "compute (reference):" << std::endl;
  }
  run_compute_shader(*comp_ref_material, *comp_ref_pipeline, stats_ref);

  if ((device.getCapabilityBits() & subgroup_required_bits) == subgroup_required_bits) {
    // clear the stats buffer
    FragmentStats stats_subgroups;
    stats_buffer->updateSubData(&stats_subgroups, sizeof(FragmentStats), 0ull);

    if constexpr (kLogStats) {
      std::cout << "------------" << std::endl;
      std::cout << "compute (subgroups):" << std::endl;
    }
    run_compute_shader(*comp_material, *comp_pipeline, stats_subgroups);

    EXPECT_EQ(stats_ref.total_fragments, stats_subgroups.total_fragments);
    EXPECT_EQ(stats_ref.min_fragments, stats_subgroups.min_fragments);
    EXPECT_EQ(stats_ref.max_fragments, stats_subgroups.max_fragments);
    EXPECT_EQ(stats_ref.num_nonzero_count, stats_subgroups.num_nonzero_count);
  } else {
    std::cout
        << "Device does not support required subgroup features. Skipping subgroups test"
        << std::endl;
  }

  // Destroy resources
  resource_mgr.destroyPipeline(std::move(draw_pipeline));
  resource_mgr.destroyPipeline(std::move(comp_pipeline));
  resource_mgr.destroyPipeline(std::move(comp_ref_pipeline));
  resource_mgr.destroyBuffer(std::move(vertex_buffer_wrapper));
  resource_mgr.destroyBuffer(std::move(index_buffer_wrapper));
  resource_mgr.destroyBuffer(std::move(indir_draw_buffer));
  resource_mgr.destroyBuffer(std::move(stats_buffer));
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  resource_mgr.destroyRenderPass(std::move(empty_render_pass));
  draw_material = nullptr;
  comp_material = nullptr;
  comp_ref_material = nullptr;
  resource_mgr.destroyTexture(std::move(storage_image));
}

#if USE_TYPED_TEST
TYPED_TEST(TypedPPLLTest, StencilThenCoverTest) {
#else
TEST_F(UntypedPPLLTest, StencilThenCoverTest) {
#endif

  auto& device = *this->device_contexts_[0];
  auto& resource_mgr = device.getResourceManager();

  static constexpr uint32_t kWidth = 320;
  static constexpr uint32_t kHeight = 240;

  // attachment manager and textures
  auto [attachment_mgr, textures] = build_attachments(
      resource_mgr,
      kWidth,
      kHeight,
      {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0},
       {PixelFormat::kDepthStencil, Framebuffer::Attachment::kDepthStencil}});

  // renderpass and framebuffer
  auto stencil_render_pass =
      resource_mgr.createRenderPass("stencil pass",
                                    attachment_mgr.getLayout(),
                                    gfx::RenderPass::ClearBits::kAll,
                                    ImageLayout::kUndefined,
                                    ImageLayout::kAttachment);
  ASSERT_NE(stencil_render_pass, nullptr);

  auto cover_render_pass =
      resource_mgr.createRenderPass("cover pass", attachment_mgr.getLayout());
  ASSERT_NE(cover_render_pass, nullptr);

  auto framebuffer = resource_mgr.createFramebuffer(
      "Test", *stencil_render_pass, attachment_mgr, kWidth, kHeight, 1u);
  ASSERT_NE(framebuffer, nullptr);

  // complex shape
  // clang-format off
  std::vector<float> shape_data{
    -0.4,  0.5,
    -0.1,  0.1,
    -0.5, -0.2,
     0.1, -0.5,
    -0.15, -0.2,
     0.5,  0.5,
     0.05,  0.3};
  // clang-format on

  // circle
  constexpr float k2Pi = 6.283185307;
  constexpr float kCircleRadius = 0.9;
  constexpr float kCircleAspect = 3.0 / 4.0;
  constexpr uint32_t kCircleSegments = 40;
  float theta_step = 1.0 / static_cast<float>(kCircleSegments);
  std::vector<float> circle_data;
  for (float theta = 0.0f; theta < 1.0001f; theta += theta_step) {
    circle_data.push_back(sin(theta * k2Pi) * kCircleAspect * kCircleRadius);
    circle_data.push_back(cos(theta * k2Pi) * kCircleRadius);
  }

  auto mesh = make_mesh<2>();
  mesh->addAttributes({{"in_position", BufferAttrType::kVec2f}});

  auto [circle_num_verts, circle_first_vert] = mesh->addVertices(circle_data);
  auto [shape_num_verts, shape_first_vert] = mesh->addVertices(shape_data);

  auto [buffer_layout, vertex_buffer_wrapper] =
      mesh->buildVertexResources(resource_mgr, "Shape");
  auto* vertex_buffer = static_cast<VertexBuffer*>(vertex_buffer_wrapper.get());

  PrimitiveAssemblyAttrInfo attr_info{{vertex_buffer, buffer_layout},
                                      {{"in_position", "in_position"}}};

  StencilThenCoverHelper helper(resource_mgr);
  auto [stencil_pipeline, cover_pipeline] =
      helper.buildResources("PPLLTests/stencilThenCoverTest_stencil.vert",
                            "PPLLTests/stencilThenCoverTest_cover.frag",
                            attr_info,
                            *stencil_render_pass);

  // Draw
  device.getCommandExecutor().setDefaultViewportAndRenderArea(0, 0, kWidth, kHeight);
  auto& cmd_list = device.getCommandList();

  // stencil pass
  cmd_list.beginRenderPass(*stencil_render_pass, *framebuffer)
      .drawVertices(
          *stencil_pipeline, *vertex_buffer, circle_num_verts, 0UL, circle_first_vert)
      .drawVertices(
          *stencil_pipeline, *vertex_buffer, shape_num_verts, 0UL, shape_first_vert)
      .endRenderPass()
      .flush(kFlushName);

  // cover pass
  cmd_list.beginRenderPass(*cover_render_pass, *framebuffer)
      .drawFullscreen(*cover_pipeline)
      .endRenderPass()
      .flush(kFlushName);

  // image compare
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "stencil_then_cover"));

  // Cleanup
  resource_mgr.destroyBuffer(std::move(vertex_buffer_wrapper));
  resource_mgr.destroyRenderPass(std::move(stencil_render_pass));
  resource_mgr.destroyRenderPass(std::move(cover_render_pass));
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
}

}  // namespace GfxDriverTests

int main(int argc, char* argv[]) {
  TestHelpers::init_logger_stderr_only(argc, argv);
  ::testing::InitGoogleTest(&argc, argv);

  int err{0};
  try {
    testing::FLAGS_gtest_death_test_style = "threadsafe";
    err = RUN_ALL_TESTS();
  } catch (const std::exception& e) {
    LOG(ERROR) << e.what();
  }

  return err;
}
