name: heavydb-dev
channels:
- conda-forge
- defaults
dependencies:
- thrift
- python >=3.7
- sqlalchemy
- coverage
- numpy
- flake8
- black
- pre-commit
- pytest-cov
- pytest-mock
- requests
- sphinx
- sphinx_rtd_theme
