name: heavydb-dev
channels:
- conda-forge
- defaults
dependencies:
- python >=3.7
- thrift>=0.13.0
- packaging
- importlib_metadata
- sqlalchemy
- requests
- coverage
- numpy
- pandas
- flake8
- black
- pre-commit
- pytest-cov
- pytest-mock
- sphinx
- sphinx_rtd_theme
