[build-system]
requires = ["flit_core >=3.3,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "heavydb"
version = "6.0.0"
requires-python = ">=3.7"
authors = [{name = "Heavy.AI", email = "community@heavy.ai"}]
description = "A DB API 2 compatible client for HeavyDB (formerly OmniSci and MapD)."
readme = "README.rst"
license = {file = "LICENSE.md"}
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Database",
    "Topic :: Scientific/Engineering",
]

dependencies = [
    "thrift >=0.13.0",
    "sqlalchemy >= 1.3",
    "numpy",
    "importlib_metadata",  # drop for python >3.7
]

[project.optional-dependencies]
rbc = [
    "rbc-project >=0.7.3"
]

doc = [
    "sphinx",
    "numpydoc",
    "sphinx-rtd-theme"
]

test = [
    "pytest",
    "coverage",
    "pytest-mock",
    "pandas"
]

dev = [
    "heavydb[doc]",
    "heavydb[test]",
    "pre-commit",
    "flit"
]

[project.urls]
Home = "https://github.com/heavyai/heavydb"
Source = "https://github.com/heavyai/heavydb"

[tool.flit.sdist]
exclude = [
    "tests/*", "ci/*",
    "*.yml", "*.yaml", ".*"]

[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ["py37", "py38", "py39", "py310"]
exclude = '''
(
  /(
      tests/test_data
    | omnisci/common
    | omnisci/completion_hints
    | omnisci/extension_functions
    | omnisci/serialized_result_set
    | omnisci/thrift
    | docs
    | benchmarks
    | scripts
    | .eggs
  )/
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rsx -v"
testpaths = [
    "tests",
]
