#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2019-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set -e
set -x

PREFIX=/usr/local/mapd-deps

function untar_deps(){
  local deps_file="$1"
  if [ -f "$deps_file" ]; then
    echo "Extracting $deps_file..."
    sudo tar xf ${deps_file}
    sudo rm -f ${deps_file}
  else
    echo "Error: ${deps_file} is not a valid file."
    exit 1
  fi
}

# Establish distro
source /etc/os-release
if [ "$ID" == "ubuntu" ] ; then
  if [ "$VERSION_ID" != "22.04" ]; then
    echo "Ubuntu 22.04 is the only Debian-based OS supported by this script"
    exit 1
  fi
elif [ "$ID" == "rocky" ] ; then
  if [ "${VERSION_ID:0:1}" != "8" ] ; then
    echo "Rocky Linux 8.x is the only RedHat-based OS supported by this script"
    exit 1
  fi
else
  echo "Only Debian- and RedHat-based OSs are supported by this script"
  exit 1
fi

# Parse inputs
UPDATE_PACKAGES=false
UPDATE_OPTIONS=
FLAG=latest
ENABLE=false
LIBRARY_TYPE=
INCLUDED_FILES_DIR=
TSAN=false

function help_msg(){
  cat << _HELP
  $0 --testing [Insert 'testing' into tar ball file name]
     --custom=<extra options to insert into tar ball file name>
     --enable [Install profile entry in /etc/profile.d]
     --static|--shared [ Insert either '-static' or '-shared' in the generated tar ball name]
     --tsan [Insert the label -tsan into the tar ball name]
     --help
     --included-files-dir=<directory containing the supporting files -
                                  common-functions.sh,
                                  dependency tar ball - see note tar ball naming convention
     --cache=<directory to check for archives and to 'cache' downloaded files>
     --update-options [Additional options for apt/dnf update]


     [ This script is designed to set up a build environment for Heavy.AI.  It installs a
       dependency tar ball [generated by mapd-deps-ubuntu.sh or mapd-deps-rockylinux.sh
       into /usr/local/mapd-deps.

       It also installs a number of 'host' level packages.

       It requires administrator/root access (via sudo) to run.

       The script can be used to install the dependency stack into a docker container via a
       'docker build' process.  The docker build files are avaliable in the heavy.ai repository
       under 'docker/build'. Installing into a docker container is the recommended approach]

     [ Notes on the naming convention used for the tar ball.

       The script will auto generate the name of the included tar ball based on operating system,
       architecture of the host being used and on the command line options.
       The basic format is -
       'mapd-deps-<ubuntu22.04|rockylinux8><|-tsan><-static|-shared><-x86_64|aarch64><-custom labels>.tar.xz'
       eg.
       mapd-deps-rockylinux8-static-x86_64-20251209-7e3387ba1.tar.xz
       mapd-deps-ubuntu22.04-shared-x86_64-20251208-cc8302bb8.tar.xz]
_HELP
  exit
}
while (( $# )); do
  case "$1" in
    --update-packages)
      UPDATE_PACKAGES=true
      ;;
    --update-options=*)
      UPDATE_OPTIONS="${1#*=}"
      ;;
    --custom=*)
      FLAG="${1#*=}"
      ;;
    --enable)
      ENABLE=true
      ;;
    --static)
      LIBRARY_TYPE=static
      ;;
    --shared)
      LIBRARY_TYPE=shared
      ;;
    --included-files-dir=*)
      INCLUDED_FILES_DIR="${1#*=}"
      ;;
    --tsan)
      TSAN=true
      ;;
    --help)
      help_msg
      ;;
    *)
      echo "Unexpected argument $1"
      exit
      ;;
  esac
  shift
done

# Validate LIBRARY_TYPE
if [ "$ID" == "ubuntu" ] &&  [ "$LIBRARY_TYPE" == "" ] ; then
  echo "ERROR - Library type must be specified for Ubuntu installs (--static or --shared)"
  exit
fi

# Establish architecture
ARCH=$(uname -m)


# update packages if requested
# pass options to allow dodging broken updates if necessary (e.g. --ignore=package1,package2)
if [ "${UPDATE_PACKAGES}" = "true" ]; then
  if [ "$ID" == "ubuntu" ] ; then
    apt update -y ${UPDATE_OPTIONS}
  elif [ "$ID" == "rocky" ] ; then
    dnf update -y ${UPDATE_OPTIONS}
  fi
fi

# do we have sudo?
if [[ ! -x "$(command -v sudo)" ]]; then
  if [ "$EUID" -eq 0 ] ; then
    if [ "$ID" == "ubuntu" ]; then
      apt install -y sudo
    else
      dnf install -y sudo
    fi
  else
    echo "ERROR - sudo not installed and not running as root"
    exit
  fi
fi

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## Set the INCLUDED_FILES_DIR to script dir if not set
## If calling this script from a docker build command
## INCLUDED_FILES_DIR must be available from the docker
## build context
: ${INCLUDED_FILES_DIR:=${SCRIPTS_DIR}}
if [[ ! -f "${INCLUDED_FILES_DIR}/common-functions.sh" ]] ; then
    echo "Error: Can not locate ${INCLUDED_FILES_DIR}/common-functions.sh"
    exit 1
fi
pwd
ls -ltr
echo "INCLUDED_FILES_DIR [${INCLUDED_FILES_DIR}]"
source ${INCLUDED_FILES_DIR}/common-functions.sh

# Distro-specific installations
if [ "$ID" == "ubuntu" ] ; then
  install_required_ubuntu_packages

  sudo apt install -y gcc-11 g++-11

  # Set up gcc-11 as default gcc
  sudo update-alternatives \
    --install /usr/bin/gcc gcc /usr/bin/gcc-11 1100 \
    --slave /usr/bin/g++ g++ /usr/bin/g++-11
  sudo update-alternatives --set gcc /usr/bin/gcc-11

  sudo mkdir -p $PREFIX
  pushd $PREFIX

  OS=ubuntu${VERSION_ID}
  TARBALL_TSAN=""
  if [ "$TSAN" = "true" ]; then
    TARBALL_TSAN="-tsan"
  fi
  TARBALL_FILENAME=mapd-deps-${OS}${TARBALL_TSAN}-${LIBRARY_TYPE}-${ARCH}-${FLAG}.tar.xz

  ## The tarball needs to be accessible to the build process.
  TARBALL_FILENAME=${INCLUDED_FILES_DIR}/${TARBALL_FILENAME}
  untar_deps ${TARBALL_FILENAME}
  popd

  generate_mapd_deps_sh "$PREFIX"
  install_profile_entry "$PREFIX" "$ENABLE"
elif [ "$ID" == "rocky" ] ; then
  sudo dnf groupinstall -y "Development Tools"

  install_required_rockylinux_packages

  sudo mkdir -p $PREFIX
  pushd $PREFIX
  OS=rockylinux8
  TARBALL_TSAN=""
  if [ "$TSAN" = "true" ]; then
    TARBALL_TSAN="-tsan"
  fi
  TARBALL_FILENAME=mapd-deps-${OS}${TARBALL_TSAN}-${LIBRARY_TYPE}-${ARCH}-${FLAG}.tar.xz
  TARBALL_FILENAME=${INCLUDED_FILES_DIR}/${TARBALL_FILENAME}
  untar_deps ${TARBALL_FILENAME}
  popd

  generate_mapd_deps_sh "$PREFIX"
  install_profile_entry "$PREFIX" "$ENABLE"
  source $PREFIX/mapd-deps.sh
fi
exit 0
