/*
 * SPDX-FileCopyrightText: Copyright (c) 2021-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#extension GL_KHR_shader_subgroup_vote: enable
#extension GL_KHR_shader_subgroup_arithmetic: enable
#extension GL_KHR_shader_subgroup_ballot: enable

layout (local_size_x = <workgroupSize>, local_size_y = 1, local_size_z = 1) in;

layout(r32ui) uniform restrict readonly uimage2D fragment_count_image;

layout(std430) buffer PPLL_TEST_COUNTERS_SSBO {
  uint64_t total_fragment_count;
  uint32_t num_nonzero_count;
  uint32_t min_fragment_count;
  uint32_t max_fragment_count;
} stats;

layout(std430) uniform FRAGMENT_STATS_UBO_TYPE {
  uvec2 image_size;
};

void main() {
  if (gl_GlobalInvocationID.x >= image_size.x) {
    return;
  }

  uint32_t value = imageLoad(fragment_count_image, ivec2(gl_GlobalInvocationID.xy)).r;
  bool have_fragments = value > 0;

  uint32_t local_min_value = have_fragments ? value : 0xFFFFFFFF;

  if (subgroupAny(have_fragments)) {
    uint32_t subgroup_sum = subgroupAdd(value);
    uint32_t subgroup_min = subgroupMin(local_min_value);
    uint32_t subgroup_max = subgroupMax(value);
    // Get bitmask for invocations that have fragments and count the bits to get the
    // number of pixels with at least 1 fragment
    uvec4 ballot = subgroupBallot(have_fragments);
    uint32_t subgroup_nonzero_count = subgroupBallotBitCount(ballot);

    // A single invocation in the subgroup will do the atomic operation
    if (subgroupElect()) {
      atomicAdd(stats.total_fragment_count, subgroup_sum);
      atomicAdd(stats.num_nonzero_count, subgroup_nonzero_count);
      atomicMin(stats.min_fragment_count, subgroup_min);
      atomicMax(stats.max_fragment_count, subgroup_max);
    }
  }
}
