# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: MIT

include(FindPackageHandleStandardArgs)

find_path(LLVMSPIRVLib_INCLUDE_DIR
  NAMES LLVMSPIRVLib/LLVMSPIRVLib.h LLVMSPIRVLib/LLVMSPIRVOpts.h
)
find_library(LLVMSPIRVLib_LIBRARY
  NAMES LLVMSPIRVLib
)

MESSAGE(STATUS "LLVMSPIRVLib_LIBRARY: " ${LLVMSPIRVLib_LIBRARY})
MESSAGE(STATUS "LLVMSPIRVLib_INCLUDE_DIR: " ${LLVMSPIRVLib_INCLUDE_DIR})
MESSAGE(STATUS "LLVMSPIRVLib_INCLUDE_DIRS: " ${LLVMSPIRVLib_INCLUDE_DIRS})

find_package_handle_standard_args(LLVMSPIRVLib
  REQUIRED_VARS
    LLVMSPIRVLib_INCLUDE_DIR
    LLVMSPIRVLib_LIBRARY
  HANDLE_COMPONENTS
)
mark_as_advanced(LLVMSPIRVLib_LIBRARY LLVMSPIRVLib_INCLUDE_DIR)

if(LLVMSPIRVLib_FOUND)
    list(APPEND LLVMSPIRVLib_LIBRARIES ${LLVMSPIRVLib_LIBRARY} ${CMAKE_DL_LIBS})
    list(APPEND LLVMSPIRVLib_INCLUDE_DIRS ${LLVMSPIRVLib_INCLUDE_DIR})
endif()


MESSAGE(STATUS "LLVMSPIRVLib_LIBRARIES: " ${LLVMSPIRVLib_LIBRARY})
MESSAGE(STATUS "LLVMSPIRVLib_INCLUDE_DIRS: " ${LLVMSPIRVLib_INCLUDE_DIRS})
