/*
 * SPDX-FileCopyrightText: Copyright (c) 2021-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "Tests/RenderTests/GfxDriver/GfxDriverTestFixtures.h"

#include <memory>
#include <string>

#include "GfxDriver/Drivers/Vulkan/VulkanPlatform.h"
#include "GfxDriver/Pipeline/Material.h"
#include "GfxDriver/Pipeline/Pipeline.h"
#include "GfxDriver/Pipeline/PipelineDescriptor.h"
#include "GfxDriver/ShaderCompiler/Library.h"
#include "GfxDriver/ShaderCompiler/ShaderManager.h"
#include "Tests/RenderTests/Utils/AttachmentUtils.h"
#include "Tests/RenderTests/Utils/GoldenImage.h"
#include "Tests/RenderTests/Utils/ShaderUtils.h"
#include "Tests/TestHelpers.h"

/**
 * GfxExperimentalTests
 *
 * - Golden image tests
 *
 * - Shader files can be added using the ShaderManifest.json file
 *   in the path specified by g_shaders_path
 *
 * - All images using ExperimentalTestBase can be regenerated by enabling
 *   regenerate_golden_images below
 *
 * */
namespace GfxDriverTests {

// Render dimensions for all tests (golden images 320x240)
static constexpr uint32_t render_width = 320;
static constexpr uint32_t render_height = 240;

// Flag to force writing of all golden image files
static constexpr bool regenerate_golden_images = false;

// File paths
namespace {
static std::string g_golden_images_path(std::string(RENDER_TESTS_PATH) +
                                        "GfxExperimental/golden_images/");
static std::string g_shaders_path(std::string(RENDER_TESTS_PATH) +
                                  "GfxExperimental/shaders/");

static std::string_view kFlushName{"GfxExperimentalTest"};
}  // namespace

//
// GfxExperimentalTestShaderLibrary
//
class GfxExperimentalTestShaderLibrary {
 public:
  static void init(Library& library) {
    library.addFromManifestFile("ShaderManifest.json", g_shaders_path);
  }
};

//
// ExperimentalTestBase fixture template
//
template <typename GTEST_BASE,
          typename DRIVER_TYPE,
          typename SHADER_LIBRARY = GfxExperimentalTestShaderLibrary>
class ExperimentalTestBase
    : public DeviceContextTest<GTEST_BASE, DRIVER_TYPE, SHADER_LIBRARY> {
 protected:
  using Base = DeviceContextTest<GTEST_BASE, DRIVER_TYPE, SHADER_LIBRARY>;

  void SetUp() override {
    Base::SetUp();
    golden_image_ = std::make_unique<GoldenImage>(
        g_golden_images_path, this->driver_->getType(), regenerate_golden_images);
  }
  void TearDown() override { Base::TearDown(); }

  std::unique_ptr<GoldenImage> golden_image_;
};

#define USE_TYPED_TEST 0

#if USE_TYPED_TEST
template <typename DRIVER_TYPE>
using TypedExperimentalTest =
    ExperimentalTestBase<::testing::Test, DRIVER_TYPE, GfxExperimentalTestShaderLibrary>;
TYPED_TEST_SUITE(TypedExperimentalTest, DriverTypes);
using VulkanExperimentalTest = ExperimentalTestBase<::testing::Test, VulkanDriver>;
#else
using ExperimentalTest = ExperimentalTestBase<::testing::Test, VulkanDriver>;
#endif

//
// Mesh Shader Draw Triangle Test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedExperimentalTest, MeshShaderDrawTriangleTest) {
#else
TEST_F(ExperimentalTest, MeshShaderDrawTriangleTest) {
#endif
  auto& device = *this->device_contexts_[0];

  if (!any_bits_set(device.getCapabilityBits() & DeviceCapabilityBits::kMeshShaders)) {
    GTEST_SKIP() << "Device does not support mesh shaders";
  }

  // Generate spirv
  auto caches = this->gfx_context_->getShaderManager().createCacheVectorFromTemplate(
      {{"ExperimentalTests/meshShaderTriangleTest.mesh"},
       {"ExperimentalTests/meshShaderTriangleTest.frag"}});
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("MeshShaderTriangleTest", caches);
  ASSERT_NE(material, nullptr);

  // attachment manager and textures
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        render_width,
                        render_height,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

  // renderpass and framebuffer
  auto render_pass = resource_mgr.createRenderPass("MeshShaderTriangleTest",
                                                   attachment_mgr.getLayout(),
                                                   gfx::RenderPass::ClearBits::kAll,
                                                   ImageLayout::kUndefined,
                                                   ImageLayout::kAttachment);
  ASSERT_NE(render_pass, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer("MeshShaderTriangleTest",
                                                    *render_pass,
                                                    attachment_mgr,
                                                    render_width,
                                                    render_height,
                                                    1u);
  ASSERT_NE(framebuffer, nullptr);

  // pipeline
  PipelineDescriptor pipeline_desc;
  pipeline_desc.setFaceCullMode(FaceCullMode::kNone);
  auto pipeline = resource_mgr.createGraphicsPipeline("Test", *material, pipeline_desc);

  pipeline->create(*render_pass);

  // render via command list
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();
  cmd_list.beginRenderPass(*render_pass, *framebuffer)
      .drawMeshTasks(*pipeline, 1u, 1u, 1u)
      .endRenderPass()
      .flush(kFlushName);

  // Compare to golden image
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "mesh_shader_draw_triangle_test"));

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  material = nullptr;
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
}

//
// Mesh Shader Workgroup ID Test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedExperimentalTest, MeshShaderWorkgroupIDTest) {
#else
TEST_F(ExperimentalTest, MeshShaderWorkgroupIDTest) {
#endif
  auto& device = *this->device_contexts_[0];

  if (!any_bits_set(device.getCapabilityBits() & DeviceCapabilityBits::kMeshShaders)) {
    GTEST_SKIP() << "Device does not support mesh shaders";
  }

  static constexpr uint32_t num_tasks = 32;
  static constexpr uint32_t num_quads = 16;

  // Check device meets required limits
  auto const& limits = device.getLimits();
  ASSERT_GE(limits.max_mesh_workgroup_size[0], num_tasks);
  ASSERT_GE(limits.max_mesh_output_vertices, num_quads * 4);
  ASSERT_GE(limits.max_mesh_output_primitives, num_quads * 2);

  // Generate spirv
  auto const& shader_mgr = this->gfx_context_->getShaderManager();
  auto builders = shader_mgr.createBuilderVector(
      {{"ExperimentalTests/meshShaderWorkgroupIDTest.mesh"},
       {"ExperimentalTests/meshShaderWorkgroupIDTest.frag"}});

  builders[0]->replaceFirstTag("numQuads", std::to_string(num_quads));
  builders[0]->replaceFirstTag("numTasks", std::to_string(num_tasks));

  auto caches = shader_mgr.createCacheVector(std::move(builders));
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("meshShaderWorkgroupIDTest", caches);
  ASSERT_NE(material, nullptr);

  // attachment manager and textures
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        render_width,
                        render_height,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

  // renderpass and framebuffer
  auto render_pass = resource_mgr.createRenderPass("meshShaderWorkgroupIDTest",
                                                   attachment_mgr.getLayout(),
                                                   gfx::RenderPass::ClearBits::kAll,
                                                   ImageLayout::kUndefined,
                                                   ImageLayout::kAttachment);
  ASSERT_NE(render_pass, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer("meshShaderWorkgroupIDTest",
                                                    *render_pass,
                                                    attachment_mgr,
                                                    render_width,
                                                    render_height,
                                                    1u);
  ASSERT_NE(framebuffer, nullptr);

  std::array<float, 2> dimensions{static_cast<float>(render_width),
                                  static_cast<float>(render_height)};
  ASSERT_NO_THROW(material->setUniformAttribute("imageSize", dimensions));
  ASSERT_NO_THROW(material->updateDescriptorSets());

  // pipeline
  PipelineDescriptor pipeline_desc;
  pipeline_desc.setFaceCullMode(FaceCullMode::kNone);
  auto pipeline = resource_mgr.createGraphicsPipeline(
      "meshShaderWorkgroupIDTest", *material, pipeline_desc);

  pipeline->create(*render_pass);

  // render via command list
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();
  cmd_list.beginRenderPass(*render_pass, *framebuffer)
      .drawMeshTasks(*pipeline, num_tasks, 1u, 1u)
      .endRenderPass()
      .flush(kFlushName);

  // Compare to golden image
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "mesh_shader_workgroup_id_test"));

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  material = nullptr;
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
}

//
// Mesh Shader Points test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedExperimentalTest, MeshShaderPointsTest) {
#else
TEST_F(ExperimentalTest, MeshShaderPointsTest) {
#endif
  auto& device = *this->device_contexts_[0];

  if (!any_bits_set(device.getCapabilityBits() & DeviceCapabilityBits::kMeshShaders)) {
    GTEST_SKIP() << "Device does not support mesh shaders";
  }

  static constexpr uint32_t num_local_workgroups = 32;
  static constexpr uint32_t num_global_workgroups = 16;
  static constexpr uint32_t num_points = num_local_workgroups * num_global_workgroups;

  // Check device meets required limits
  auto const& limits = device.getLimits();
  ASSERT_GE(limits.max_mesh_workgroup_size[0], num_global_workgroups);
  ASSERT_GE(limits.max_mesh_output_vertices, num_local_workgroups);
  ASSERT_GE(limits.max_mesh_output_primitives, num_local_workgroups);

  // Generate spirv
  auto const& shader_mgr = this->gfx_context_->getShaderManager();
  auto builders =
      shader_mgr.createBuilderVector({{"ExperimentalTests/meshShaderPointsTest.mesh"},
                                      {"ExperimentalTests/meshShaderPointsTest.frag"}});

  builders[0]->replaceFirstTag("numLocalWorkgroups",
                               std::to_string(num_local_workgroups));
  builders[0]->replaceFirstTag("numGlobalWorkgroups",
                               std::to_string(num_global_workgroups));
  builders[0]->replaceFirstTag("numPoints", std::to_string(num_points));

  auto caches = shader_mgr.createCacheVector(std::move(builders));
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("meshShaderPointsTest", caches);
  ASSERT_NE(material, nullptr);

  // attachment manager and textures
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        render_width,
                        render_height,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

  // renderpass and framebuffer
  auto render_pass = resource_mgr.createRenderPass("meshShaderPointsTest",
                                                   attachment_mgr.getLayout(),
                                                   gfx::RenderPass::ClearBits::kAll,
                                                   ImageLayout::kUndefined,
                                                   ImageLayout::kAttachment);
  ASSERT_NE(render_pass, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer("meshShaderPointsTest",
                                                    *render_pass,
                                                    attachment_mgr,
                                                    render_width,
                                                    render_height,
                                                    1u);
  ASSERT_NE(framebuffer, nullptr);

  std::array<float, 2> dimensions{static_cast<float>(render_width),
                                  static_cast<float>(render_height)};
  ASSERT_NO_THROW(material->setUniformAttribute("imageSize", dimensions));
  ASSERT_NO_THROW(material->updateDescriptorSets());

  // pipeline
  PipelineDescriptor pipeline_desc;
  pipeline_desc.setFaceCullMode(FaceCullMode::kNone);
  auto pipeline = resource_mgr.createGraphicsPipeline(
      "meshShaderWorkgroupIDTest", *material, pipeline_desc);

  pipeline->create(*render_pass);

  // render via command list
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();
  cmd_list.beginRenderPass(*render_pass, *framebuffer)
      .drawMeshTasks(*pipeline, num_global_workgroups, 1u, 1u)
      .endRenderPass()
      .flush(kFlushName);

  // Compare to golden image
  EXPECT_TRUE(this->golden_image_->write(
      *framebuffer, Framebuffer::Attachment::kColor0, "mesh_shader_points_test"));

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  material = nullptr;
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
}

//
// Task Shader Test
//
#if USE_TYPED_TEST
TYPED_TEST(TypedExperimentalTest, TaskShaderTest) {
#else
TEST_F(ExperimentalTest, TaskShaderTest) {
#endif
  auto& device = *this->device_contexts_[0];

  if (!any_bits_set(device.getCapabilityBits() & DeviceCapabilityBits::kTaskShaders)) {
    GTEST_SKIP() << "Device does not support task shaders";
  }

  static constexpr uint32_t num_quads = 16;
  static constexpr uint32_t max_mesh_tasks = 32;

  // Check device meets required limits
  auto const& limits = device.getLimits();
  ASSERT_GE(limits.max_mesh_output_vertices, num_quads * 4);
  ASSERT_GE(limits.max_mesh_output_primitives, num_quads * 2);

  // Generate spirv
  auto const& shader_mgr = this->gfx_context_->getShaderManager();
  auto builders =
      shader_mgr.createBuilderVector({{"ExperimentalTests/taskShaderTest.task"},
                                      {"ExperimentalTests/taskShaderTest.mesh"},
                                      {"ExperimentalTests/taskShaderTest.frag"}});

  builders[0]->replaceFirstTag("numQuads", std::to_string(num_quads));
  builders[1]->replaceFirstTag("maxNumMeshTasks", std::to_string(max_mesh_tasks));
  builders[1]->replaceFirstTag("maxNumQuads", std::to_string(num_quads));

  auto caches = shader_mgr.createCacheVector(std::move(builders));
  ASSERT_TRUE(validate_shader_caches(caches));

  auto& resource_mgr = device.getResourceManager();

  // material
  auto material = resource_mgr.createMaterial("TaskShaderTest", caches);
  ASSERT_NE(material, nullptr);

  // attachment manager and textures
  auto [attachment_mgr, textures] =
      build_attachments(resource_mgr,
                        render_width,
                        render_height,
                        {{PixelFormat::kRGBA8, Framebuffer::Attachment::kColor0}});

  // renderpass and framebuffer
  auto render_pass = resource_mgr.createRenderPass("TaskShaderTest",
                                                   attachment_mgr.getLayout(),
                                                   gfx::RenderPass::ClearBits::kAll,
                                                   ImageLayout::kUndefined,
                                                   ImageLayout::kAttachment);
  ASSERT_NE(render_pass, nullptr);
  auto framebuffer = resource_mgr.createFramebuffer(
      "TaskShaderTest", *render_pass, attachment_mgr, render_width, render_height, 1u);
  ASSERT_NE(framebuffer, nullptr);

  static constexpr uint32_t task_count = render_height;
  ASSERT_GE(limits.max_mesh_workgroup_count[0], task_count);

  std::array<uint32_t, 2> dimensions{render_width, render_height};
  // Set image size in both task and mesh stages (we don't support shared UBOs)
  ASSERT_NO_THROW(material->setUniformAttribute("imageSize", dimensions));
  ASSERT_NO_THROW(material->setUniformAttribute("imageSizeM", dimensions));
  ASSERT_NO_THROW(material->updateDescriptorSets());

  // pipeline
  PipelineDescriptor pipeline_desc;
  pipeline_desc.setFaceCullMode(FaceCullMode::kNone);
  auto pipeline =
      resource_mgr.createGraphicsPipeline("TaskShaderTest", *material, pipeline_desc);

  pipeline->create(*render_pass);

  // render via command list
  device.getCommandExecutor().setDefaultViewportAndRenderArea(
      0, 0, render_width, render_height);
  auto& cmd_list = device.getCommandList();
  cmd_list.beginRenderPass(*render_pass, *framebuffer)
      .drawMeshTasks(*pipeline, task_count, 1u, 1u)
      .endRenderPass()
      .flush(kFlushName);

  // Compare to golden image
  EXPECT_TRUE(this->golden_image_->compare(
      *framebuffer, Framebuffer::Attachment::kColor0, "task_shader_test", false, 1u, 1u));

  // destroy resources
  resource_mgr.destroyPipeline(std::move(pipeline));
  material = nullptr;
  resource_mgr.destroyFramebuffer(std::move(framebuffer));
  for (auto& texture : textures) {
    resource_mgr.destroyTexture(std::move(texture));
  }
  resource_mgr.destroyRenderPass(std::move(render_pass));
}

}  // namespace GfxDriverTests

int main(int argc, char* argv[]) {
  TestHelpers::init_logger_stderr_only(argc, argv);
  ::testing::InitGoogleTest(&argc, argv);

  int err{0};
  try {
    testing::FLAGS_gtest_death_test_style = "threadsafe";
    err = RUN_ALL_TESTS();
  } catch (const std::exception& e) {
    LOG(ERROR) << e.what();
  }

  return err;
}
