name: Reusable test action
on:
  workflow_call: 
    inputs:
      cuda_compiler_version:
        type: string
        default: None
      is_conda_updated:
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      cuda_compiler_version: ${{ inputs.cuda_compiler_version }}
      PREFIX: distr
      CONDA_ENV: omnisci-dev

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Set env context
        run: |
          echo CONDA_PATH=$CONDA >>$GITHUB_ENV
          echo RUN_STAMP=${{ runner.os }}-${{ (env.cuda_compiler_version != 'None') && format('cuda{0}', env.cuda_compiler_version) || 'CPU' }} >>$GITHUB_ENV
          echo CONDA_ENV_PATH=$CONDA/envs/${{ env.CONDA_ENV }} >>$GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.RUN_STAMP }}-build

      - name: Unpack build files
        run: |
          tar -zxf build.tgz

      - name: Download new Conda
        if: ${{ inputs.is_conda_updated == 'true' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.RUN_STAMP }}-conda

      - name: Download old Conda
        if: ${{ inputs.is_conda_updated != 'true' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
          name: ${{ env.RUN_STAMP }}-conda
          search_artifacts: true

      - name: Unpack Conda
        run: |
          mkdir -p ${{ env.CONDA_ENV_PATH }}
          tar -zxf conda.tgz -C ${{ env.CONDA_ENV_PATH }}

      - name: Run tests
        run: |
          sudo sh -c 'echo 2 >/proc/sys/vm/overcommit_memory'
          $CONDA/bin/conda run -n omnisci-dev bash scripts/conda/test.sh

